// Code generated by capnpc-go. DO NOT EDIT.

package directory

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
	strconv "strconv"
)

type Kind uint16

// Kind_TypeID is the unique identifier for the type Kind.
const Kind_TypeID = 0xe9f9d97f31757757

// Values of Kind.
const (
	Kind_file      Kind = 0
	Kind_directory Kind = 1
	Kind_link      Kind = 2
)

// String returns the enum's constant name.
func (c Kind) String() string {
	switch c {
	case Kind_file:
		return "file"
	case Kind_directory:
		return "directory"
	case Kind_link:
		return "link"

	default:
		return ""
	}
}

// KindFromString returns the enum value with a name,
// or the zero value if there's no such value.
func KindFromString(c string) Kind {
	switch c {
	case "file":
		return Kind_file
	case "directory":
		return Kind_directory
	case "link":
		return Kind_link

	default:
		return 0
	}
}

type Kind_List = capnp.EnumList[Kind]

func NewKind_List(s *capnp.Segment, sz int32) (Kind_List, error) {
	return capnp.NewEnumList[Kind](s, sz)
}

type Entry capnp.Struct
type Entry_owner Entry
type Entry_Which uint16

const (
	Entry_Which_none   Entry_Which = 0
	Entry_Which_target Entry_Which = 1
	Entry_Which_blob   Entry_Which = 2
)

func (w Entry_Which) String() string {
	const s = "nonetargetblob"
	switch w {
	case Entry_Which_none:
		return s[0:4]
	case Entry_Which_target:
		return s[4:10]
	case Entry_Which_blob:
		return s[10:14]

	}
	return "Entry_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Entry_TypeID is the unique identifier for the type Entry.
const Entry_TypeID = 0xc5f5b8c9abf71b27

func NewEntry(s *capnp.Segment) (Entry, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 5})
	return Entry(st), err
}

func NewRootEntry(s *capnp.Segment) (Entry, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 5})
	return Entry(st), err
}

func ReadRootEntry(msg *capnp.Message) (Entry, error) {
	root, err := msg.Root()
	return Entry(root.Struct()), err
}

func (s Entry) String() string {
	str, _ := text.Marshal(0xc5f5b8c9abf71b27, capnp.Struct(s))
	return str
}

func (s Entry) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Entry) DecodeFromPtr(p capnp.Ptr) Entry {
	return Entry(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Entry) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Entry) Which() Entry_Which {
	return Entry_Which(capnp.Struct(s).Uint16(20))
}
func (s Entry) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Entry) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Entry) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Entry) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Entry) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Entry) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Entry) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Entry) Size() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Entry) SetSize(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Entry) Kind() Kind {
	return Kind(capnp.Struct(s).Uint16(8))
}

func (s Entry) SetKind(v Kind) {
	capnp.Struct(s).SetUint16(8, uint16(v))
}

func (s Entry) Tags() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.TextList(p.List()), err
}

func (s Entry) HasTags() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Entry) SetTags(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewTags sets the tags field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s Entry) NewTags(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s Entry) Priority() int16 {
	return int16(capnp.Struct(s).Uint16(10) ^ 5)
}

func (s Entry) SetPriority(v int16) {
	capnp.Struct(s).SetUint16(10, uint16(v)^5)
}

func (s Entry) Owner() Entry_owner { return Entry_owner(s) }

func (s Entry_owner) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Entry_owner) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Entry_owner) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Entry_owner) Uid() uint32 {
	return capnp.Struct(s).Uint32(12)
}

func (s Entry_owner) SetUid(v uint32) {
	capnp.Struct(s).SetUint32(12, v)
}

func (s Entry_owner) Gid() uint32 {
	return capnp.Struct(s).Uint32(16)
}

func (s Entry_owner) SetGid(v uint32) {
	capnp.Struct(s).SetUint32(16, v)
}

func (s Entry) SetNone() {
	capnp.Struct(s).SetUint16(20, 0)

}

func (s Entry) Target() (string, error) {
	if capnp.Struct(s).Uint16(20) != 1 {
		panic("Which() != target")
	}
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Entry) HasTarget() bool {
	if capnp.Struct(s).Uint16(20) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(2)
}

func (s Entry) TargetBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Entry) SetTarget(v string) error {
	capnp.Struct(s).SetUint16(20, 1)
	return capnp.Struct(s).SetText(2, v)
}

func (s Entry) Blob() ([]byte, error) {
	if capnp.Struct(s).Uint16(20) != 2 {
		panic("Which() != blob")
	}
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s Entry) HasBlob() bool {
	if capnp.Struct(s).Uint16(20) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(2)
}

func (s Entry) SetBlob(v []byte) error {
	capnp.Struct(s).SetUint16(20, 2)
	return capnp.Struct(s).SetData(2, v)
}

func (s Entry) Children() (Entry_List, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return Entry_List(p.List()), err
}

func (s Entry) HasChildren() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Entry) SetChildren(v Entry_List) error {
	return capnp.Struct(s).SetPtr(3, v.ToPtr())
}

// NewChildren sets the children field to a newly
// allocated Entry_List, preferring placement in s's segment.
func (s Entry) NewChildren(n int32) (Entry_List, error) {
	l, err := NewEntry_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Entry_List{}, err
	}
	err = capnp.Struct(s).SetPtr(3, l.ToPtr())
	return l, err
}
func (s Entry) Scores() (capnp.Float64List, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return capnp.Float64List(p.List()), err
}

func (s Entry) HasScores() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Entry) SetScores(v capnp.Float64List) error {
	return capnp.Struct(s).SetPtr(4, v.ToPtr())
}

// NewScores sets the scores field to a newly
// allocated capnp.Float64List, preferring placement in s's segment.
func (s Entry) NewScores(n int32) (capnp.Float64List, error) {
	l, err := capnp.NewFloat64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Float64List{}, err
	}
	err = capnp.Struct(s).SetPtr(4, l.ToPtr())
	return l, err
}
func (s Entry) Hidden() bool {
	return !capnp.Struct(s).Bit(176)
}

func (s Entry) SetHidden(v bool) {
	capnp.Struct(s).SetBit(176, !v)
}

// Entry_List is a list of Entry.
type Entry_List = capnp.StructList[Entry]

// NewEntry creates a new list of Entry.
func NewEntry_List(s *capnp.Segment, sz int32) (Entry_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 5}, sz)
	return capnp.StructList[Entry](l), err
}

// Entry_Future is a wrapper for a Entry promised by a client call.
type Entry_Future struct{ *capnp.Future }

func (f Entry_Future) Struct() (Entry, error) {
	p, err := f.Future.Ptr()
	return Entry(p.Struct()), err
}
func (p Entry_Future) Owner() Entry_owner_Future { return Entry_owner_Future{p.Future} }

// Entry_owner_Future is a wrapper for a Entry_owner promised by a client call.
type Entry_owner_Future struct{ *capnp.Future }

func (f Entry_owner_Future) Struct() (Entry_owner, error) {
	p, err := f.Future.Ptr()
	return Entry_owner(p.Struct()), err
}

type Base capnp.Client

// Base_TypeID is the unique identifier for the type Base.
const Base_TypeID = 0xbaca77b1a8ce9252

func (c Base) Ping(ctx context.Context, params func(Base_ping_Params) error) (Base_ping_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xbaca77b1a8ce9252,
			MethodID:      0,
			InterfaceName: "directory.capnp:Base",
			MethodName:    "ping",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Base_ping_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Base_ping_Results_Future{Future: ans.Future()}, release

}

func (c Base) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Base) String() string {
	return "Base(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Base) AddRef() Base {
	return Base(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Base) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Base) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Base) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Base) DecodeFromPtr(p capnp.Ptr) Base {
	return Base(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Base) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Base) IsSame(other Base) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Base) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Base) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Base_Server is a Base with a local implementation.
type Base_Server interface {
	Ping(context.Context, Base_ping) error
}

// Base_NewServer creates a new Server from an implementation of Base_Server.
func Base_NewServer(s Base_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Base_Methods(nil, s), s, c)
}

// Base_ServerToClient creates a new Client from an implementation of Base_Server.
// The caller is responsible for calling Release on the returned Client.
func Base_ServerToClient(s Base_Server) Base {
	return Base(capnp.NewClient(Base_NewServer(s)))
}

// Base_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Base_Methods(methods []server.Method, s Base_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xbaca77b1a8ce9252,
			MethodID:      0,
			InterfaceName: "directory.capnp:Base",
			MethodName:    "ping",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Ping(ctx, Base_ping{call})
		},
	})

	return methods
}

// Base_ping holds the state for a server call to Base.ping.
// See server.Call for documentation.
type Base_ping struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Base_ping) Args() Base_ping_Params {
	return Base_ping_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Base_ping) AllocResults() (Base_ping_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Base_ping_Results(r), err
}

// Base_List is a list of Base.
type Base_List = capnp.CapList[Base]

// NewBase_List creates a new list of Base.
func NewBase_List(s *capnp.Segment, sz int32) (Base_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Base](l), err
}

type Base_ping_Params capnp.Struct

// Base_ping_Params_TypeID is the unique identifier for the type Base_ping_Params.
const Base_ping_Params_TypeID = 0xc301d0ea70e80c45

func NewBase_ping_Params(s *capnp.Segment) (Base_ping_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Base_ping_Params(st), err
}

func NewRootBase_ping_Params(s *capnp.Segment) (Base_ping_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Base_ping_Params(st), err
}

func ReadRootBase_ping_Params(msg *capnp.Message) (Base_ping_Params, error) {
	root, err := msg.Root()
	return Base_ping_Params(root.Struct()), err
}

func (s Base_ping_Params) String() string {
	str, _ := text.Marshal(0xc301d0ea70e80c45, capnp.Struct(s))
	return str
}

func (s Base_ping_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Base_ping_Params) DecodeFromPtr(p capnp.Ptr) Base_ping_Params {
	return Base_ping_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Base_ping_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Base_ping_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Base_ping_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Base_ping_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Base_ping_Params_List is a list of Base_ping_Params.
type Base_ping_Params_List = capnp.StructList[Base_ping_Params]

// NewBase_ping_Params creates a new list of Base_ping_Params.
func NewBase_ping_Params_List(s *capnp.Segment, sz int32) (Base_ping_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Base_ping_Params](l), err
}

// Base_ping_Params_Future is a wrapper for a Base_ping_Params promised by a client call.
type Base_ping_Params_Future struct{ *capnp.Future }

func (f Base_ping_Params_Future) Struct() (Base_ping_Params, error) {
	p, err := f.Future.Ptr()
	return Base_ping_Params(p.Struct()), err
}

type Base_ping_Results capnp.Struct

// Base_ping_Results_TypeID is the unique identifier for the type Base_ping_Results.
const Base_ping_Results_TypeID = 0x9bd08cddbe78c460

func NewBase_ping_Results(s *capnp.Segment) (Base_ping_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Base_ping_Results(st), err
}

func NewRootBase_ping_Results(s *capnp.Segment) (Base_ping_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Base_ping_Results(st), err
}

func ReadRootBase_ping_Results(msg *capnp.Message) (Base_ping_Results, error) {
	root, err := msg.Root()
	return Base_ping_Results(root.Struct()), err
}

func (s Base_ping_Results) String() string {
	str, _ := text.Marshal(0x9bd08cddbe78c460, capnp.Struct(s))
	return str
}

func (s Base_ping_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Base_ping_Results) DecodeFromPtr(p capnp.Ptr) Base_ping_Results {
	return Base_ping_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Base_ping_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Base_ping_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Base_ping_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Base_ping_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Base_ping_Results) Pong() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Base_ping_Results) HasPong() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Base_ping_Results) PongBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Base_ping_Results) SetPong(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Base_ping_Results_List is a list of Base_ping_Results.
type Base_ping_Results_List = capnp.StructList[Base_ping_Results]

// NewBase_ping_Results creates a new list of Base_ping_Results.
func NewBase_ping_Results_List(s *capnp.Segment, sz int32) (Base_ping_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Base_ping_Results](l), err
}

// Base_ping_Results_Future is a wrapper for a Base_ping_Results promised by a client call.
type Base_ping_Results_Future struct{ *capnp.Future }

func (f Base_ping_Results_Future) Struct() (Base_ping_Results, error) {
	p, err := f.Future.Ptr()
	return Base_ping_Results(p.Struct()), err
}

type Directory capnp.Client

// Directory_TypeID is the unique identifier for the type Directory.
const Directory_TypeID = 0xe2a7a501f9721fb0

func (c Directory) Lookup(ctx context.Context, params func(Directory_lookup_Params) error) (Directory_lookup_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe2a7a501f9721fb0,
			MethodID:      0,
			InterfaceName: "directory.capnp:Directory",
			MethodName:    "lookup",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Directory_lookup_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Directory_lookup_Results_Future{Future: ans.Future()}, release

}

func (c Directory) Add(ctx context.Context, params func(Directory_add_Params) error) (Directory_add_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe2a7a501f9721fb0,
			MethodID:      1,
			InterfaceName: "directory.capnp:Directory",
			MethodName:    "add",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Directory_add_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Directory_add_Results_Future{Future: ans.Future()}, release

}

func (c Directory) Store(ctx context.Context, params func(Directory_store_Params) error) (Directory_store_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe2a7a501f9721fb0,
			MethodID:      2,
			InterfaceName: "directory.capnp:Directory",
			MethodName:    "store",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Directory_store_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Directory_store_Results_Future{Future: ans.Future()}, release

}

func (c Directory) Fail(ctx context.Context, params func(Directory_fail_Params) error) (Directory_fail_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe2a7a501f9721fb0,
			MethodID:      3,
			InterfaceName: "directory.capnp:Directory",
			MethodName:    "fail",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Directory_fail_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Directory_fail_Results_Future{Future: ans.Future()}, release

}

func (c Directory) Ping(ctx context.Context, params func(Base_ping_Params) error) (Base_ping_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xbaca77b1a8ce9252,
			MethodID:      0,
			InterfaceName: "directory.capnp:Base",
			MethodName:    "ping",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Base_ping_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Base_ping_Results_Future{Future: ans.Future()}, release

}

func (c Directory) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Directory) String() string {
	return "Directory(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Directory) AddRef() Directory {
	return Directory(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Directory) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Directory) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Directory) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Directory) DecodeFromPtr(p capnp.Ptr) Directory {
	return Directory(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Directory) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Directory) IsSame(other Directory) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Directory) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Directory) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Directory_Server is a Directory with a local implementation.
type Directory_Server interface {
	Lookup(context.Context, Directory_lookup) error

	Add(context.Context, Directory_add) error

	Store(context.Context, Directory_store) error

	Fail(context.Context, Directory_fail) error

	Ping(context.Context, Base_ping) error
}

// Directory_NewServer creates a new Server from an implementation of Directory_Server.
func Directory_NewServer(s Directory_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Directory_Methods(nil, s), s, c)
}

// Directory_ServerToClient creates a new Client from an implementation of Directory_Server.
// The caller is responsible for calling Release on the returned Client.
func Directory_ServerToClient(s Directory_Server) Directory {
	return Directory(capnp.NewClient(Directory_NewServer(s)))
}

// Directory_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Directory_Methods(methods []server.Method, s Directory_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 5)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe2a7a501f9721fb0,
			MethodID:      0,
			InterfaceName: "directory.capnp:Directory",
			MethodName:    "lookup",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Lookup(ctx, Directory_lookup{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe2a7a501f9721fb0,
			MethodID:      1,
			InterfaceName: "directory.capnp:Directory",
			MethodName:    "add",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Add(ctx, Directory_add{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe2a7a501f9721fb0,
			MethodID:      2,
			InterfaceName: "directory.capnp:Directory",
			MethodName:    "store",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Store(ctx, Directory_store{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe2a7a501f9721fb0,
			MethodID:      3,
			InterfaceName: "directory.capnp:Directory",
			MethodName:    "fail",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Fail(ctx, Directory_fail{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xbaca77b1a8ce9252,
			MethodID:      0,
			InterfaceName: "directory.capnp:Base",
			MethodName:    "ping",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Ping(ctx, Base_ping{call})
		},
	})

	return methods
}

// Directory_lookup holds the state for a server call to Directory.lookup.
// See server.Call for documentation.
type Directory_lookup struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Directory_lookup) Args() Directory_lookup_Params {
	return Directory_lookup_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Directory_lookup) AllocResults() (Directory_lookup_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Directory_lookup_Results(r), err
}

// Directory_add holds the state for a server call to Directory.add.
// See server.Call for documentation.
type Directory_add struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Directory_add) Args() Directory_add_Params {
	return Directory_add_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Directory_add) AllocResults() (Directory_add_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Directory_add_Results(r), err
}

// Directory_store holds the state for a server call to Directory.store.
// See server.Call for documentation.
type Directory_store struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Directory_store) Args() Directory_store_Params {
	return Directory_store_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Directory_store) AllocResults() (Directory_store_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Directory_store_Results(r), err
}

// Directory_fail holds the state for a server call to Directory.fail.
// See server.Call for documentation.
type Directory_fail struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Directory_fail) Args() Directory_fail_Params {
	return Directory_fail_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Directory_fail) AllocResults() (Directory_fail_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Directory_fail_Results(r), err
}

// Directory_List is a list of Directory.
type Directory_List = capnp.CapList[Directory]

// NewDirectory_List creates a new list of Directory.
func NewDirectory_List(s *capnp.Segment, sz int32) (Directory_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Directory](l), err
}

type Directory_lookup_Params capnp.Struct

// Directory_lookup_Params_TypeID is the unique identifier for the type Directory_lookup_Params.
const Directory_lookup_Params_TypeID = 0xbdceec867d57c38a

func NewDirectory_lookup_Params(s *capnp.Segment) (Directory_lookup_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Directory_lookup_Params(st), err
}

func NewRootDirectory_lookup_Params(s *capnp.Segment) (Directory_lookup_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Directory_lookup_Params(st), err
}

func ReadRootDirectory_lookup_Params(msg *capnp.Message) (Directory_lookup_Params, error) {
	root, err := msg.Root()
	return Directory_lookup_Params(root.Struct()), err
}

func (s Directory_lookup_Params) String() string {
	str, _ := text.Marshal(0xbdceec867d57c38a, capnp.Struct(s))
	return str
}

func (s Directory_lookup_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Directory_lookup_Params) DecodeFromPtr(p capnp.Ptr) Directory_lookup_Params {
	return Directory_lookup_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Directory_lookup_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Directory_lookup_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Directory_lookup_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Directory_lookup_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Directory_lookup_Params) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Directory_lookup_Params) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Directory_lookup_Params) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Directory_lookup_Params) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Directory_lookup_Params_List is a list of Directory_lookup_Params.
type Directory_lookup_Params_List = capnp.StructList[Directory_lookup_Params]

// NewDirectory_lookup_Params creates a new list of Directory_lookup_Params.
func NewDirectory_lookup_Params_List(s *capnp.Segment, sz int32) (Directory_lookup_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Directory_lookup_Params](l), err
}

// Directory_lookup_Params_Future is a wrapper for a Directory_lookup_Params promised by a client call.
type Directory_lookup_Params_Future struct{ *capnp.Future }

func (f Directory_lookup_Params_Future) Struct() (Directory_lookup_Params, error) {
	p, err := f.Future.Ptr()
	return Directory_lookup_Params(p.Struct()), err
}

type Directory_lookup_Results capnp.Struct

// Directory_lookup_Results_TypeID is the unique identifier for the type Directory_lookup_Results.
const Directory_lookup_Results_TypeID = 0xbfa32d5415523a4c

func NewDirectory_lookup_Results(s *capnp.Segment) (Directory_lookup_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Directory_lookup_Results(st), err
}

func NewRootDirectory_lookup_Results(s *capnp.Segment) (Directory_lookup_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Directory_lookup_Results(st), err
}

func ReadRootDirectory_lookup_Results(msg *capnp.Message) (Directory_lookup_Results, error) {
	root, err := msg.Root()
	return Directory_lookup_Results(root.Struct()), err
}

func (s Directory_lookup_Results) String() string {
	str, _ := text.Marshal(0xbfa32d5415523a4c, capnp.Struct(s))
	return str
}

func (s Directory_lookup_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Directory_lookup_Results) DecodeFromPtr(p capnp.Ptr) Directory_lookup_Results {
	return Directory_lookup_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Directory_lookup_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Directory_lookup_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Directory_lookup_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Directory_lookup_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Directory_lookup_Results) Entry() (Entry, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Entry(p.Struct()), err
}

func (s Directory_lookup_Results) HasEntry() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Directory_lookup_Results) SetEntry(v Entry) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewEntry sets the entry field to a newly
// allocated Entry struct, preferring placement in s's segment.
func (s Directory_lookup_Results) NewEntry() (Entry, error) {
	ss, err := NewEntry(capnp.Struct(s).Segment())
	if err != nil {
		return Entry{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Directory_lookup_Results_List is a list of Directory_lookup_Results.
type Directory_lookup_Results_List = capnp.StructList[Directory_lookup_Results]

// NewDirectory_lookup_Results creates a new list of Directory_lookup_Results.
func NewDirectory_lookup_Results_List(s *capnp.Segment, sz int32) (Directory_lookup_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Directory_lookup_Results](l), err
}

// Directory_lookup_Results_Future is a wrapper for a Directory_lookup_Results promised by a client call.
type Directory_lookup_Results_Future struct{ *capnp.Future }

func (f Directory_lookup_Results_Future) Struct() (Directory_lookup_Results, error) {
	p, err := f.Future.Ptr()
	return Directory_lookup_Results(p.Struct()), err
}
func (p Directory_lookup_Results_Future) Entry() Entry_Future {
	return Entry_Future{Future: p.Future.Field(0, nil)}
}

type Directory_add_Params capnp.Struct

// Directory_add_Params_TypeID is the unique identifier for the type Directory_add_Params.
const Directory_add_Params_TypeID = 0x89cc814d4ec61fd2

func NewDirectory_add_Params(s *capnp.Segment) (Directory_add_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Directory_add_Params(st), err
}

func NewRootDirectory_add_Params(s *capnp.Segment) (Directory_add_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Directory_add_Params(st), err
}

func ReadRootDirectory_add_Params(msg *capnp.Message) (Directory_add_Params, error) {
	root, err := msg.Root()
	return Directory_add_Params(root.Struct()), err
}

func (s Directory_add_Params) String() string {
	str, _ := text.Marshal(0x89cc814d4ec61fd2, capnp.Struct(s))
	return str
}

func (s Directory_add_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Directory_add_Params) DecodeFromPtr(p capnp.Ptr) Directory_add_Params {
	return Directory_add_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Directory_add_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Directory_add_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Directory_add_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Directory_add_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Directory_add_Params) A() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s Directory_add_Params) SetA(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s Directory_add_Params) B() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s Directory_add_Params) SetB(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

// Directory_add_Params_List is a list of Directory_add_Params.
type Directory_add_Params_List = capnp.StructList[Directory_add_Params]

// NewDirectory_add_Params creates a new list of Directory_add_Params.
func NewDirectory_add_Params_List(s *capnp.Segment, sz int32) (Directory_add_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[Directory_add_Params](l), err
}

// Directory_add_Params_Future is a wrapper for a Directory_add_Params promised by a client call.
type Directory_add_Params_Future struct{ *capnp.Future }

func (f Directory_add_Params_Future) Struct() (Directory_add_Params, error) {
	p, err := f.Future.Ptr()
	return Directory_add_Params(p.Struct()), err
}

type Directory_add_Results capnp.Struct

// Directory_add_Results_TypeID is the unique identifier for the type Directory_add_Results.
const Directory_add_Results_TypeID = 0xa866cf96ca80354f

func NewDirectory_add_Results(s *capnp.Segment) (Directory_add_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Directory_add_Results(st), err
}

func NewRootDirectory_add_Results(s *capnp.Segment) (Directory_add_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Directory_add_Results(st), err
}

func ReadRootDirectory_add_Results(msg *capnp.Message) (Directory_add_Results, error) {
	root, err := msg.Root()
	return Directory_add_Results(root.Struct()), err
}

func (s Directory_add_Results) String() string {
	str, _ := text.Marshal(0xa866cf96ca80354f, capnp.Struct(s))
	return str
}

func (s Directory_add_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Directory_add_Results) DecodeFromPtr(p capnp.Ptr) Directory_add_Results {
	return Directory_add_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Directory_add_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Directory_add_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Directory_add_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Directory_add_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Directory_add_Results) Sum() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s Directory_add_Results) SetSum(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

// Directory_add_Results_List is a list of Directory_add_Results.
type Directory_add_Results_List = capnp.StructList[Directory_add_Results]

// NewDirectory_add_Results creates a new list of Directory_add_Results.
func NewDirectory_add_Results_List(s *capnp.Segment, sz int32) (Directory_add_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[Directory_add_Results](l), err
}

// Directory_add_Results_Future is a wrapper for a Directory_add_Results promised by a client call.
type Directory_add_Results_Future struct{ *capnp.Future }

func (f Directory_add_Results_Future) Struct() (Directory_add_Results, error) {
	p, err := f.Future.Ptr()
	return Directory_add_Results(p.Struct()), err
}

type Directory_store_Params capnp.Struct

// Directory_store_Params_TypeID is the unique identifier for the type Directory_store_Params.
const Directory_store_Params_TypeID = 0xb6a0c064c90fd49d

func NewDirectory_store_Params(s *capnp.Segment) (Directory_store_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Directory_store_Params(st), err
}

func NewRootDirectory_store_Params(s *capnp.Segment) (Directory_store_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Directory_store_Params(st), err
}

func ReadRootDirectory_store_Params(msg *capnp.Message) (Directory_store_Params, error) {
	root, err := msg.Root()
	return Directory_store_Params(root.Struct()), err
}

func (s Directory_store_Params) String() string {
	str, _ := text.Marshal(0xb6a0c064c90fd49d, capnp.Struct(s))
	return str
}

func (s Directory_store_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Directory_store_Params) DecodeFromPtr(p capnp.Ptr) Directory_store_Params {
	return Directory_store_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Directory_store_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Directory_store_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Directory_store_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Directory_store_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Directory_store_Params) Entry() (Entry, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Entry(p.Struct()), err
}

func (s Directory_store_Params) HasEntry() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Directory_store_Params) SetEntry(v Entry) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewEntry sets the entry field to a newly
// allocated Entry struct, preferring placement in s's segment.
func (s Directory_store_Params) NewEntry() (Entry, error) {
	ss, err := NewEntry(capnp.Struct(s).Segment())
	if err != nil {
		return Entry{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Directory_store_Params_List is a list of Directory_store_Params.
type Directory_store_Params_List = capnp.StructList[Directory_store_Params]

// NewDirectory_store_Params creates a new list of Directory_store_Params.
func NewDirectory_store_Params_List(s *capnp.Segment, sz int32) (Directory_store_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Directory_store_Params](l), err
}

// Directory_store_Params_Future is a wrapper for a Directory_store_Params promised by a client call.
type Directory_store_Params_Future struct{ *capnp.Future }

func (f Directory_store_Params_Future) Struct() (Directory_store_Params, error) {
	p, err := f.Future.Ptr()
	return Directory_store_Params(p.Struct()), err
}
func (p Directory_store_Params_Future) Entry() Entry_Future {
	return Entry_Future{Future: p.Future.Field(0, nil)}
}

type Directory_store_Results capnp.Struct

// Directory_store_Results_TypeID is the unique identifier for the type Directory_store_Results.
const Directory_store_Results_TypeID = 0x9d550f8ec19ac8a3

func NewDirectory_store_Results(s *capnp.Segment) (Directory_store_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Directory_store_Results(st), err
}

func NewRootDirectory_store_Results(s *capnp.Segment) (Directory_store_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Directory_store_Results(st), err
}

func ReadRootDirectory_store_Results(msg *capnp.Message) (Directory_store_Results, error) {
	root, err := msg.Root()
	return Directory_store_Results(root.Struct()), err
}

func (s Directory_store_Results) String() string {
	str, _ := text.Marshal(0x9d550f8ec19ac8a3, capnp.Struct(s))
	return str
}

func (s Directory_store_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Directory_store_Results) DecodeFromPtr(p capnp.Ptr) Directory_store_Results {
	return Directory_store_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Directory_store_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Directory_store_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Directory_store_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Directory_store_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Directory_store_Results) Stored() (Entry, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Entry(p.Struct()), err
}

func (s Directory_store_Results) HasStored() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Directory_store_Results) SetStored(v Entry) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStored sets the stored field to a newly
// allocated Entry struct, preferring placement in s's segment.
func (s Directory_store_Results) NewStored() (Entry, error) {
	ss, err := NewEntry(capnp.Struct(s).Segment())
	if err != nil {
		return Entry{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Directory_store_Results) Count() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s Directory_store_Results) SetCount(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

// Directory_store_Results_List is a list of Directory_store_Results.
type Directory_store_Results_List = capnp.StructList[Directory_store_Results]

// NewDirectory_store_Results creates a new list of Directory_store_Results.
func NewDirectory_store_Results_List(s *capnp.Segment, sz int32) (Directory_store_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Directory_store_Results](l), err
}

// Directory_store_Results_Future is a wrapper for a Directory_store_Results promised by a client call.
type Directory_store_Results_Future struct{ *capnp.Future }

func (f Directory_store_Results_Future) Struct() (Directory_store_Results, error) {
	p, err := f.Future.Ptr()
	return Directory_store_Results(p.Struct()), err
}
func (p Directory_store_Results_Future) Stored() Entry_Future {
	return Entry_Future{Future: p.Future.Field(0, nil)}
}

type Directory_fail_Params capnp.Struct

// Directory_fail_Params_TypeID is the unique identifier for the type Directory_fail_Params.
const Directory_fail_Params_TypeID = 0x8458cd4b4c2dce17

func NewDirectory_fail_Params(s *capnp.Segment) (Directory_fail_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Directory_fail_Params(st), err
}

func NewRootDirectory_fail_Params(s *capnp.Segment) (Directory_fail_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Directory_fail_Params(st), err
}

func ReadRootDirectory_fail_Params(msg *capnp.Message) (Directory_fail_Params, error) {
	root, err := msg.Root()
	return Directory_fail_Params(root.Struct()), err
}

func (s Directory_fail_Params) String() string {
	str, _ := text.Marshal(0x8458cd4b4c2dce17, capnp.Struct(s))
	return str
}

func (s Directory_fail_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Directory_fail_Params) DecodeFromPtr(p capnp.Ptr) Directory_fail_Params {
	return Directory_fail_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Directory_fail_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Directory_fail_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Directory_fail_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Directory_fail_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Directory_fail_Params) Why() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Directory_fail_Params) HasWhy() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Directory_fail_Params) WhyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Directory_fail_Params) SetWhy(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Directory_fail_Params_List is a list of Directory_fail_Params.
type Directory_fail_Params_List = capnp.StructList[Directory_fail_Params]

// NewDirectory_fail_Params creates a new list of Directory_fail_Params.
func NewDirectory_fail_Params_List(s *capnp.Segment, sz int32) (Directory_fail_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Directory_fail_Params](l), err
}

// Directory_fail_Params_Future is a wrapper for a Directory_fail_Params promised by a client call.
type Directory_fail_Params_Future struct{ *capnp.Future }

func (f Directory_fail_Params_Future) Struct() (Directory_fail_Params, error) {
	p, err := f.Future.Ptr()
	return Directory_fail_Params(p.Struct()), err
}

type Directory_fail_Results capnp.Struct

// Directory_fail_Results_TypeID is the unique identifier for the type Directory_fail_Results.
const Directory_fail_Results_TypeID = 0x88c30cb9b3cdc662

func NewDirectory_fail_Results(s *capnp.Segment) (Directory_fail_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Directory_fail_Results(st), err
}

func NewRootDirectory_fail_Results(s *capnp.Segment) (Directory_fail_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Directory_fail_Results(st), err
}

func ReadRootDirectory_fail_Results(msg *capnp.Message) (Directory_fail_Results, error) {
	root, err := msg.Root()
	return Directory_fail_Results(root.Struct()), err
}

func (s Directory_fail_Results) String() string {
	str, _ := text.Marshal(0x88c30cb9b3cdc662, capnp.Struct(s))
	return str
}

func (s Directory_fail_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Directory_fail_Results) DecodeFromPtr(p capnp.Ptr) Directory_fail_Results {
	return Directory_fail_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Directory_fail_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Directory_fail_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Directory_fail_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Directory_fail_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Directory_fail_Results_List is a list of Directory_fail_Results.
type Directory_fail_Results_List = capnp.StructList[Directory_fail_Results]

// NewDirectory_fail_Results creates a new list of Directory_fail_Results.
func NewDirectory_fail_Results_List(s *capnp.Segment, sz int32) (Directory_fail_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Directory_fail_Results](l), err
}

// Directory_fail_Results_Future is a wrapper for a Directory_fail_Results promised by a client call.
type Directory_fail_Results_Future struct{ *capnp.Future }

func (f Directory_fail_Results_Future) Struct() (Directory_fail_Results, error) {
	p, err := f.Future.Ptr()
	return Directory_fail_Results(p.Struct()), err
}

const schema_d8f4c0e7a1b2c3d4 = "x\xda\x9cUm\x88T\xd5\x1b\x7f~\xe7\x9c\xbbwv" +
	"\xdd\xf5\xce\xf5\xce\xfe\x05\xff\xc8\xc0\xb2P.\xec\xa2[" +
	"~hHf4\x97|Ys\xee\xae\x8b\x0a\x0a\xde\xdd" +
	"{]/\x8ew\xa6;3\x8c\x1bH\x09\x1a\x19\xd2\xdb" +
	"\x07\xa1BH$|\x89\xc0\x0c\"\x83\xca\xd8\x94\x944" +
	"\x15\x85\xfaP\x1f\x84\xe8\x05\xa1>\x14\xe1\x87\xbaq\xce" +
	"\xec\xbc\xac\xa3[\xf4\xed\xf0;\xcf\xf9=\xbf\xf3\xbc." +
	"\xfd\x8ee\xc4\xb2\xae\x97\xdb\x88\xd9\xc3Z[\xb4\xf0j" +
	"\xff\xf0\xfa+[\x0e\x90\xb9\x08D\x1at\xa2G\xfa\xf9" +
	" \x08\xd6r\x9e&D\xe3\x17\xaf\xbc\x7f\xaes\xfa\x85" +
	"\xaa\x81\x90\xf7c<\x05\x12\xd1\x8d\xe4\xc5\xa76\xec\xff" +
	"\xf2\x10\xd9\x8bP\xbbZ\xc1\xfb\xe4\xd3!^!D;" +
	">\xdf\xfb\xc9\xb7\x87\xaf\xbdIfw\x9d\xfb\x18_ " +
	"\x0dN)\xee\xe3_\xbc\xf1\xd9K\xc6\xd8\xd1\x19\x86\xaa" +
	"\xc5%\xbeJZ\\W\x14\x1b\x97?w\xf9\xc8W;" +
	"O6\xfb\xe8\x17UyBR\x1c\xbdi\\r\xcf\xbf" +
	"\xf5A\xb3\xfe1\x91\x92\x06\xdb\x95\xc1\xc8kWO\xbe" +
	"W\xb9\xfc\x11\x99q\x1e\xdd\x9c>{\xec\x87\xf3\xbf}" +
	"M\x04k\x9f8m\x1d\x94\x84\xd6~\xf1\xa4uJ\x9e" +
	"\xa2\x17\xa77\xef{\xfe\xce\xd5\x8f\x9b\xd9^\x15J\xcf" +
	"\xeb\x8am85\xd2\xbd\xa9\xff\xf8\xa7\xcd\x06\xe7\xc4:" +
	"ipA\x19\x0cu\xfeX\xf8\xf9\x1a\xa6\xab\x7fVz" +
	"\xbf\x17\x1d2\\\x0f\xfd\xff\x8fw.}\xf8\xfb\x05\xb2" +
	"\xe3hR2\xa4\xe9\x1c\x1d\xd6\x15q\xd6\xba\xa5\xcc\xaf" +
	"\x8b\x13\x8c\x10\x9dI\x86w\xf1\xf6\x89\xdb-\xba\x8f\xe9" +
	"7\xacwuiyJ\xd7a\xad\x8d-$\x8a6W" +
	"\xca\xcb\x9e\xfd\xe6\xeeOd\xc6\xd9,\xeb\xc7b\xa7\xad" +
	"\x951\xf9\xcb\x15\xb1\x8d\x84\xe8\x97[\x07\x8f\x0c\xdfy" +
	"\xe2W\xb2\xff\x07\xde\xd0\xd4\xad\xe9 \xb2\xc6b\xb7\x09" +
	"\xd6\xd6X\x85\xfa#\xd7\x0f\xbd\x89R>\xe4S\x03\x13" +
	"N!(\xa4V\xcf\x00S\x03;\x1d?\xd7\x9bM:" +
	"\xa1\xb3\xa7h\x0b.\x88\x04\x88\xcc\xae\x1e\";\xc6a" +
	"'\x18\xf4\xca\xae)t\x12C'\xe1\x1f\xa9F\xd2^" +
	"\xb1\x9c+\x15\xe72t\\\xb77\xeb\x18\xcae\xac\xee" +
	"r\xc9\x02\"\xbb\x97\xc3^\xca`\x02\x09Y$f\xbf" +
	"\x04\x1f\xe6\xb0\x1fe\x80\x03A\x0c\x82\x80\xf1\xda\xa9\xd5" +
	"\xcd*\xa7\xe8\x0d\x14\xfc`\xb2wD)\xc1\xaco\xf5" +
	"5\xbee\x14\xf2\xc1d\xcb\xbfD\xab\xdcb)\x1fz" +
	"3lEjV\x9cj(\xae\x0b\x1el\x08N\xab\x97" +
	".\xe2\x8d\xe4\x10\x10'$'\xf2\xe5\xa0\x84\x181\xc4" +
	"\xe6\x8e\xa9\x0c\xd5\x88\x97T\xae\x1f\x94\x9eby\x0f4" +
	"b\xd0\xe6\xa6\xaa~#\x9dmI\xf5`\x83+\xe9\x05" +
	"\xa5p\xaaUp\x9d\x175^C\xc69\x0b\xd8\x82k" +
	"D\xf5^AmP\x98f\x1f1S\xd3\x0d\x99\x8a\x0c" +
	"\xb2\x983\xc4\xb9|~w\xb9\xd0[\xd5F\x0fJX" +
	"\xe0\xec\xf1\xfeM\xc2f\xd8j\x19\xa3\xff\xfa\xd9\xfb\xd4" +
	"\xd4\x8cBj\x0dHrH\xb2\xc9\x88,\xady\xb3V" +
	"\xa2\x8fh\xf4qp\x8c\xaeA\xbdF\xac!\x05g$" +
	"<\x0c\x06\x93\x89\x04\x18\x91\xb5V\xe1\xab%\x9e\x958" +
	"G\x02\x9c\xc8\xda\xa0\xf05\x12w%.\xb4\x04\x04`" +
	"9XG4\xbaC\xe29I\xaf\xa1i(X>\x06" +
	"\x89u\xb5EQB\x8e6\xcbV$\xc3\xd2x\x0b\x18" +
	"\x16\xeb\x7fE,\x81\x98\x9c\x14H\x11\x8df\xe5\xcd6" +
	"y\x13\xfbS\xde\xb4\x13Y[\xd5\x9bM\xf2f\x87t" +
	"\xdc\xce\x13\xe8 \xb2\xb6+\xc7\xdb$\xbeW\xe2\x1d\"" +
	"\x81yDVY1\x15$~X\xe2\xf3\xce$\xd0\x09" +
	"X\x87\x14~@\xe2\xaf\xe0\x9eD\x1aE\xff\x19\x0f\xed" +
	"\xc4\xd0N0v\xfb\x81\x0b\xa31\x03\x090\x08F\xc9" +
	"\x99,b>!\xcb\xa1\xde\xcd'D\x85\xd0\xcf\x87~" +
	"i\x8a\x88\xc0\x89i\\#$\xf3\x95\xc0\x0b\x8d \x1f" +
	"x\xd4\x96.9\xe1\xa4W\xaa;\x1a\xcf\xe5\xc7\xd1E" +
	"\x0c]\x84hb\x97\x9fsC/\x90\xafg\x88g\x17" +
	"\xc2|B\xba8\x91\x0f\xbd\xba\xe3yU\xc7\xe9]\xbe" +
	"\xebz\x01@L\x03\x9a\xca\x85\xdd[\x89P\xe5\x10W" +
	"\x0dR[G\xa8\xad\x1d\xf3\xe9\x141\xd3\xd3\x81\xfa\xf6" +
	"EmE\x9a[{\x88\x99\x1bt\xb0\xfaRDm\xc1" +
	"\x9a+\x07\x89\x99\xcbu\xf0\xfa\xc2Gm\xb1\x9bKd" +
	"\xd3-\xd6\xd3\xd5\x0e\xc8@w\\7\x83\xa4j\xfd\x0c" +
	"\x0c9\xa13\xb0\x05\x9av\xe9\xfdj\xd9X\xef\x07\xae" +
	"\xd4\xde)\xeb\xd2\\\xdc'\x03bv\x8f\x10\x81\xc9\xc6" +
	"&c\xa7\x9f\xf3\xea\xef\x08SF\xce\x0fv\xb7FB" +
	"\xf5\xc4@\xbe\xa2\x07^(\x07g\x9c'\xa0\xc9\xc9\xd9" +
	"\xd3<\xebE\x02mrt\xf64F\xa7^\xf6\xdd\xda" +
	"|\xd4'\x1b\xe7\xbf\x03\x00\x00\xff\xff}:G\x95"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_d8f4c0e7a1b2c3d4,
		Nodes: []uint64{
			0x8458cd4b4c2dce17,
			0x88c30cb9b3cdc662,
			0x89cc814d4ec61fd2,
			0x9bd08cddbe78c460,
			0x9d550f8ec19ac8a3,
			0xa866cf96ca80354f,
			0xb6a0c064c90fd49d,
			0xbaca77b1a8ce9252,
			0xbdceec867d57c38a,
			0xbfa32d5415523a4c,
			0xc301d0ea70e80c45,
			0xc5f5b8c9abf71b27,
			0xe2a7a501f9721fb0,
			0xe9f9d97f31757757,
			0xf043ec4c9685d5ef,
		},
		Compressed: true,
	})
}
