//! Server protocol e2e tests

#[cfg(feature = "amqp")]
pub mod amqp;
#[cfg(feature = "arp")]
pub mod arp;
#[cfg(feature = "bgp")]
pub mod bgp;
#[cfg(feature = "bitcoin")]
pub mod bitcoin;
#[cfg(feature = "bluetooth-ble")]
pub mod bluetooth_ble;
#[cfg(feature = "bluetooth-ble-battery")]
pub mod bluetooth_ble_battery;
#[cfg(feature = "bluetooth-ble-beacon")]
pub mod bluetooth_ble_beacon;
#[cfg(feature = "bluetooth-ble-cycling")]
pub mod bluetooth_ble_cycling;
#[cfg(feature = "bluetooth-ble-data-stream")]
pub mod bluetooth_ble_data_stream;
#[cfg(feature = "bluetooth-ble-environmental")]
pub mod bluetooth_ble_environmental;
#[cfg(feature = "bluetooth-ble-file-transfer")]
pub mod bluetooth_ble_file_transfer;
#[cfg(feature = "bluetooth-ble-gamepad")]
pub mod bluetooth_ble_gamepad;
#[cfg(feature = "bluetooth-ble-heart-rate")]
pub mod bluetooth_ble_heart_rate;
#[cfg(feature = "bluetooth-ble-keyboard")]
pub mod bluetooth_ble_keyboard;
#[cfg(feature = "bluetooth-ble-mouse")]
pub mod bluetooth_ble_mouse;
#[cfg(feature = "bluetooth-ble-presenter")]
pub mod bluetooth_ble_presenter;
#[cfg(feature = "bluetooth-ble-proximity")]
pub mod bluetooth_ble_proximity;
#[cfg(feature = "bluetooth-ble-remote")]
pub mod bluetooth_ble_remote;
#[cfg(feature = "bluetooth-ble-running")]
pub mod bluetooth_ble_running;
#[cfg(feature = "bluetooth-ble-thermometer")]
pub mod bluetooth_ble_thermometer;
#[cfg(feature = "bluetooth-ble-weight-scale")]
pub mod bluetooth_ble_weight_scale;
#[cfg(feature = "bootp")]
pub mod bootp;
#[cfg(feature = "cassandra")]
pub mod cassandra;
#[cfg(feature = "coap")]
pub mod coap;
#[cfg(feature = "couchdb")]
pub mod couchdb;
#[cfg(feature = "datalink")]
pub mod datalink;
#[cfg(feature = "db2")]
pub mod db2;
#[cfg(feature = "dc")]
pub mod dc;
#[cfg(feature = "dhcp")]
pub mod dhcp;
#[cfg(feature = "dns")]
pub mod dns;
#[cfg(feature = "doh")]
pub mod doh;
#[cfg(feature = "dot")]
pub mod dot;
#[cfg(feature = "dynamo")]
pub mod dynamo;
#[cfg(feature = "elasticsearch")]
pub mod elasticsearch;
#[cfg(feature = "etcd")]
pub mod etcd;
#[cfg(feature = "ftp")]
pub mod ftp;
#[cfg(feature = "git")]
pub mod git;
#[cfg(feature = "grpc")]
pub mod grpc;
#[cfg(feature = "hls")]
pub mod hls;
#[cfg(feature = "http")]
pub mod http;
#[cfg(feature = "http2")]
pub mod http2;
#[cfg(feature = "icmp")]
pub mod icmp;
#[cfg(feature = "igmp")]
pub mod igmp;
#[cfg(feature = "imap")]
pub mod imap;
#[cfg(feature = "ipp")]
pub mod ipp;
#[cfg(feature = "ipsec")]
pub mod ipsec;
#[cfg(feature = "irc")]
pub mod irc;
#[cfg(feature = "isis")]
pub mod isis;
#[cfg(feature = "jsonrpc")]
pub mod jsonrpc;
#[cfg(feature = "kafka")]
pub mod kafka;
#[cfg(feature = "kubernetes-server")]
pub mod kubernetes;
#[cfg(feature = "ldap")]
pub mod ldap;
#[cfg(feature = "maven")]
pub mod maven;
#[cfg(feature = "mcp")]
pub mod mcp;
#[cfg(feature = "mdns")]
pub mod mdns;
#[cfg(feature = "memcached")]
pub mod memcached;
#[cfg(feature = "mercurial")]
pub mod mercurial;
#[cfg(feature = "modbus")]
pub mod modbus;
#[cfg(feature = "mongodb-server")]
pub mod mongodb;
#[cfg(feature = "mqtt")]
pub mod mqtt;
#[cfg(feature = "mssql")]
pub mod mssql;
#[cfg(feature = "mysql")]
pub mod mysql;
#[cfg(all(feature = "named_pipe", unix))]
pub mod named_pipe;
#[cfg(feature = "nfc")]
pub mod nfc;
#[cfg(feature = "nfs")]
pub mod nfs;
#[cfg(feature = "nntp")]
pub mod nntp;
#[cfg(feature = "npm")]
pub mod npm;
#[cfg(feature = "ntp")]
pub mod ntp;
#[cfg(feature = "oauth2")]
pub mod oauth2;
#[cfg(feature = "oci-registry")]
pub mod oci_registry;
#[cfg(feature = "ollama")]
pub mod ollama;
#[cfg(feature = "openai")]
pub mod openai;
#[cfg(feature = "openapi")]
pub mod openapi;
#[cfg(feature = "openid")]
pub mod openid;
#[cfg(feature = "openvpn")]
pub mod openvpn;
#[cfg(feature = "ospf")]
pub mod ospf;
#[cfg(feature = "pop3")]
pub mod pop3;
#[cfg(feature = "postgresql")]
pub mod postgresql;
#[cfg(feature = "proxy")]
pub mod proxy;
#[cfg(all(feature = "pty", unix))]
pub mod pty;
#[cfg(feature = "pypi")]
pub mod pypi;
#[cfg(feature = "quic")]
pub mod quic;
#[cfg(feature = "radius")]
pub mod radius;
#[cfg(feature = "rdp")]
pub mod rdp;
#[cfg(feature = "redis")]
pub mod redis;
#[cfg(feature = "reverse-shell")]
pub mod reverse_shell;
#[cfg(feature = "rip")]
pub mod rip;
#[cfg(feature = "rss")]
pub mod rss;
#[cfg(feature = "rtp")]
pub mod rtp;
#[cfg(feature = "rtsp")]
pub mod rtsp;
#[cfg(feature = "s3")]
pub mod s3;
#[cfg(feature = "saml-idp")]
pub mod saml_idp;
#[cfg(feature = "saml-sp")]
pub mod saml_sp;
#[cfg(feature = "sip")]
pub mod sip;
#[cfg(feature = "smb")]
pub mod smb;
#[cfg(feature = "smtp")]
pub mod smtp;
#[cfg(feature = "snmp")]
pub mod snmp;
#[cfg(feature = "snowflake")]
pub mod snowflake;
#[cfg(all(feature = "socket_file", unix))]
pub mod socket_file;
#[cfg(feature = "socks5")]
pub mod socks5;
#[cfg(feature = "spark")]
pub mod spark;
#[cfg(feature = "sqs")]
pub mod sqs;
#[cfg(feature = "ssh")]
pub mod ssh;
#[cfg(all(feature = "ssh-agent", unix))]
pub mod ssh_agent;
#[cfg(all(feature = "stdio", unix))]
pub mod stdio;
#[cfg(feature = "stun")]
pub mod stun;
#[cfg(feature = "svn")]
pub mod svn;
#[cfg(feature = "syslog")]
pub mod syslog;
#[cfg(feature = "tcp")]
pub mod tcp;
#[cfg(feature = "telnet")]
pub mod telnet;
#[cfg(feature = "tftp")]
pub mod tftp;
#[cfg(feature = "tls")]
pub mod tls;
#[cfg(feature = "tor")]
pub mod tor_integration;
#[cfg(feature = "tor")]
pub mod tor_relay;
#[cfg(feature = "torrent-dht")]
pub mod torrent_dht;
#[cfg(all(
    feature = "torrent-tracker",
    feature = "torrent-dht",
    feature = "torrent-peer"
))]
pub mod torrent_integration;
#[cfg(feature = "torrent-peer")]
pub mod torrent_peer;
#[cfg(feature = "torrent-tracker")]
pub mod torrent_tracker;
#[cfg(feature = "turn")]
pub mod turn;
#[cfg(feature = "udp")]
pub mod udp;
#[cfg(feature = "usb-fido2")]
pub mod usb_fido2;
#[cfg(feature = "usb-keyboard")]
pub mod usb_keyboard;
#[cfg(feature = "usb-mouse")]
pub mod usb_mouse;
#[cfg(feature = "usb-msc")]
pub mod usb_msc;
#[cfg(feature = "usb-serial")]
pub mod usb_serial;
#[cfg(feature = "usb-smartcard")]
pub mod usb_smartcard;
#[cfg(feature = "vnc")]
pub mod vnc;
#[cfg(feature = "webdav")]
pub mod webdav;
#[cfg(feature = "webrtc")]
pub mod webrtc;
#[cfg(feature = "webrtc")]
pub mod webrtc_signaling;
#[cfg(feature = "websocket")]
pub mod websocket;
#[cfg(feature = "whois")]
pub mod whois;
#[cfg(feature = "ndp")]
pub mod ndp;
#[cfg(feature = "dhcpv6")]
pub mod dhcpv6;
#[cfg(feature = "tuntap")]
pub mod tuntap;
#[cfg(feature = "rawip")]
pub mod rawip;
#[cfg(feature = "gtp")]
pub mod gtp;
#[cfg(feature = "m3ua")]
pub mod m3ua;
#[cfg(feature = "can")]
pub mod can;
#[cfg(feature = "lldp")]
pub mod lldp;
#[cfg(feature = "cdp")]
pub mod cdp;
#[cfg(feature = "stp")]
pub mod stp;
#[cfg(feature = "vrrp")]
pub mod vrrp;
#[cfg(feature = "hsrp")]
pub mod hsrp;
#[cfg(feature = "eapol")]
pub mod eapol;
#[cfg(feature = "wol")]
pub mod wol;
#[cfg(feature = "nats")]
pub mod nats;
#[cfg(feature = "stomp")]
pub mod stomp;
#[cfg(feature = "ident")]
pub mod ident;
#[cfg(feature = "gopher")]
pub mod gopher;
#[cfg(feature = "finger")]
pub mod finger;
#[cfg(feature = "ssdp")]
pub mod ssdp;
#[cfg(feature = "llmnr")]
pub mod llmnr;
#[cfg(feature = "netbios-ns")]
pub mod netbios_ns;
#[cfg(feature = "wireguard")]
pub mod wireguard;
#[cfg(feature = "xmlrpc")]
pub mod xmlrpc;
#[cfg(feature = "xmpp")]
pub mod xmpp;
#[cfg(feature = "yarn")]
pub mod yarn;
#[cfg(feature = "zookeeper")]
pub mod zookeeper;

// Shared test helpers - re-export from top-level for backward compatibility
pub use super::helpers;
