"""Write a Synapse config for one test: generated by Synapse itself, then pointed at a
loopback port and a data directory of its own, logging to the console, with rate limits
out of the way and no federation.

Usage: synapse_conf.py <dir> <port>
"""
import subprocess
import sys

import yaml

d, port = sys.argv[1], int(sys.argv[2])
cfg = f"{d}/homeserver.yaml"
subprocess.run(
    [sys.executable, "-m", "synapse.app.homeserver", "--server-name", "localhost",
     "--config-path", cfg, "--data-directory", d, "--generate-config",
     "--report-stats=no"],
    check=True, stdout=subprocess.DEVNULL,
)
with open(cfg) as f:
    c = yaml.safe_load(f)
c["listeners"] = [{"port": port, "bind_addresses": ["127.0.0.1"], "type": "http",
                   "tls": False, "x_forwarded": False,
                   "resources": [{"names": ["client"], "compress": False}]}]
c["database"] = {"name": "sqlite3", "args": {"database": f"{d}/homeserver.db"}}
c["log_config"] = f"{d}/log.yaml"
c["media_store_path"] = f"{d}/media"
c["trusted_key_servers"] = []
c["suppress_key_server_warning"] = True
c["federation_domain_whitelist"] = []
c["enable_registration"] = False
c["report_stats"] = False
fast = {"per_second": 1000, "burst_count": 1000}
for k in ("rc_message", "rc_registration", "rc_joins", "rc_invites", "rc_3pid_validation",
          "rc_admin_redaction", "rc_room_creation", "rc_presence"):
    c[k] = fast
c["rc_login"] = {"address": fast, "account": fast, "failed_attempts": fast}
c["rc_joins"] = {"local": fast, "remote": fast}
c["rc_invites"] = {"per_room": fast, "per_user": fast, "per_issuer": fast}
c["rc_presence"] = {"per_user": fast}
with open(cfg, "w") as f:
    yaml.safe_dump(c, f)
with open(f"{d}/log.yaml", "w") as f:
    yaml.safe_dump({
        "version": 1,
        "formatters": {"p": {"format": "%(asctime)s %(name)s %(levelname)s %(message)s"}},
        "handlers": {"console": {"class": "logging.StreamHandler", "formatter": "p"}},
        "root": {"level": "INFO", "handlers": ["console"]},
        "disable_existing_loggers": False,
    }, f)
