"""Pinned, unchanged Cap'n Proto RPC peers in an owned ROOT, used in both roles:
- pycapnp 2.2.4 (the Python binding of the C++ Cap'n Proto runtime it bundles), installed with
  --require-hashes, which runs pycapnp_peer.py in this directory;
- capnproto.org/go/capnp/v3 v3.1.0-alpha.2, built from tests/client/capnp_rpc/peer
  (go.sum-pinned; its directory.capnp.go was generated by capnpc-go and is checked in).
The tests also need the capnp compiler on PATH (apt-get install capnproto / brew install capnp),
which NetGet itself runs to compile directory.capnp. Needs Python >= 3.12 and Go 1.24 or newer.

Usage: python3 install_peers.py /absolute/owned/root
Prints the NETGET_CAPNP_PYTHON and NETGET_CAPNP_GO_PEER exports the tests read.
"""
import os, pathlib, shutil, subprocess, sys, venv

root = pathlib.Path(sys.argv[1]).resolve()
root.mkdir(parents=True, exist_ok=True)
here = pathlib.Path(__file__).resolve().parent
assert shutil.which("capnp"), "the capnp compiler is required: apt-get install capnproto (or brew install capnp)"
env = root / "venv"
if not (env / "bin" / "python").exists():
    venv.EnvBuilder(with_pip=True).create(env)
python = str(env / "bin" / "python")
subprocess.run([python, "-m", "pip", "install", "--quiet", "--disable-pip-version-check", "--require-hashes", "-r", str(here / "requirements.txt")], check=True, timeout=900)
subprocess.run([python, "-c", "import capnp; assert capnp.__version__ == '2.2.4', capnp.__version__"], check=True, timeout=60)
peer = root / "capnp-peer"
build_env = dict(os.environ, GOFLAGS="-mod=readonly", CGO_ENABLED="0")
go_dir = here.parent.parent / "client" / "capnp_rpc" / "peer"
subprocess.run(["go", "build", "-trimpath", "-o", str(peer), "."], cwd=go_dir, env=build_env, check=True, timeout=900)
subprocess.run(["go", "mod", "verify"], cwd=go_dir, env=build_env, check=True, timeout=300)
print("export NETGET_CAPNP_PYTHON=" + python)
print("export NETGET_CAPNP_GO_PEER=" + str(peer))
