//! The TUN/TAP packet layer, against literal packet bytes.
//!
//! Creating a TUN interface needs root, so the transport can never run here. What *can* run —
//! and is where every decision about what NetGet says lives — is the decoder, the builder and
//! the escalation filter. So they are tested against real header bytes written out by hand,
//! not against anything this code produced.
//!
//! Run with:
//!   ./cargo-isolated.sh test --no-default-features --features tuntap \
//!       --test server::tuntap::packet_test -- --test-threads=100

#[cfg(all(test, feature = "tuntap"))]
mod tests {
    use netget::server::tuntap::packet::{
        build_packet, checksum16, decode, ip_protocol_name, parse_mac, tcp_flag_bits,
        tcp_flag_names, DecodeError, LinkMode, PacketFilter, PacketInformation, Transport,
    };
    use serde_json::json;

    // -----------------------------------------------------------------------
    // Literal fixtures. Every byte is written out; nothing here is generated by
    // the code under test.
    // -----------------------------------------------------------------------

    /// IPv4 / ICMP echo request, 10.7.0.1 -> 10.7.0.2, id 0x1234, seq 1, payload "abcdefgh".
    ///
    /// 20-byte IP header + 8-byte ICMP header + 8-byte payload = 36 = 0x0024.
    fn ipv4_icmp_echo_request() -> Vec<u8> {
        vec![
            // ---- IPv4 ----
            0x45, // version 4, IHL 5
            0x00, // DSCP/ECN
            0x00, 0x24, // total length 36
            0xab, 0xcd, // identification
            0x40, 0x00, // flags: DF, fragment offset 0
            0x40, // TTL 64
            0x01, // protocol 1 = ICMP
            0x00, 0x00, // header checksum (not verified on decode)
            0x0a, 0x07, 0x00, 0x01, // src 10.7.0.1
            0x0a, 0x07, 0x00, 0x02, // dst 10.7.0.2
            // ---- ICMP ----
            0x08, // type 8 = echo request
            0x00, // code 0
            0x00, 0x00, // checksum
            0x12, 0x34, // identifier 4660
            0x00, 0x01, // sequence 1
            // ---- payload "abcdefgh" ----
            0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68,
        ]
    }

    /// IPv4 / TCP SYN, 192.168.1.100:54321 -> 192.168.1.1:80, seq 1, window 65535.
    fn ipv4_tcp_syn() -> Vec<u8> {
        vec![
            0x45, 0x00, 0x00, 0x28, // total length 40 = 20 + 20
            0x00, 0x01, 0x40, 0x00, 0x40, //
            0x06, // protocol 6 = TCP
            0x00, 0x00, //
            0xc0, 0xa8, 0x01, 0x64, // src 192.168.1.100
            0xc0, 0xa8, 0x01, 0x01, // dst 192.168.1.1
            // ---- TCP ----
            0xd4, 0x31, // source port 54321
            0x00, 0x50, // destination port 80
            0x00, 0x00, 0x00, 0x01, // seq 1
            0x00, 0x00, 0x00, 0x00, // ack 0
            0x50, // data offset 5 words, reserved 0
            0x02, // flags: SYN
            0xff, 0xff, // window 65535
            0x00, 0x00, // checksum
            0x00, 0x00, // urgent pointer
        ]
    }

    /// The same flow's SYN+ACK, which `tcp-syn` must NOT match.
    fn ipv4_tcp_syn_ack() -> Vec<u8> {
        let mut p = ipv4_tcp_syn();
        p[33] = 0x12; // SYN | ACK
        p
    }

    /// IPv4 / UDP, 10.0.0.1:40481 -> 8.8.8.8:53, payload "hello".
    fn ipv4_udp() -> Vec<u8> {
        vec![
            0x45, 0x00, 0x00, 0x21, // total length 33 = 20 + 8 + 5
            0x00, 0x02, 0x00, 0x00, 0x40, //
            0x11, // protocol 17 = UDP
            0x00, 0x00, //
            0x0a, 0x00, 0x00, 0x01, // src 10.0.0.1
            0x08, 0x08, 0x08, 0x08, // dst 8.8.8.8
            // ---- UDP ----
            0x9e, 0x21, // source port 40481
            0x00, 0x35, // destination port 53
            0x00, 0x0d, // length 13 = 8 + 5
            0x00, 0x00, // checksum
            0x68, 0x65, 0x6c, 0x6c, 0x6f, // "hello"
        ]
    }

    /// IPv6 / ICMPv6 echo request, 2001:db8::1 -> 2001:db8::2, id 0xabcd, seq 7.
    fn ipv6_icmpv6_echo_request() -> Vec<u8> {
        vec![
            0x60, 0x00, 0x00, 0x00, // version 6, no traffic class or flow label
            0x00, 0x10, // payload length 16 = 8 + 8
            0x3a, // next header 58 = ICMPv6
            0x40, // hop limit 64
            // src 2001:db8::1
            0x20, 0x01, 0x0d, 0xb8, 0x00, 0x00, 0x00, 0x00, //
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, //
            // dst 2001:db8::2
            0x20, 0x01, 0x0d, 0xb8, 0x00, 0x00, 0x00, 0x00, //
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, //
            // ---- ICMPv6 ----
            0x80, // type 128 = echo request
            0x00, // code 0
            0x00, 0x00, // checksum
            0xab, 0xcd, // identifier 43981
            0x00, 0x07, // sequence 7
            0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, // "12345678"
        ]
    }

    fn tun(frame: &[u8]) -> Result<netget::server::tuntap::packet::DecodedPacket, DecodeError> {
        decode(frame, PacketInformation::None, LinkMode::Tun)
    }

    // -----------------------------------------------------------------------
    // Decoding
    // -----------------------------------------------------------------------

    #[test]
    fn decodes_an_ipv4_icmp_echo_request() {
        let p = tun(&ipv4_icmp_echo_request()).expect("decodes");

        assert_eq!(p.ip_version, 4);
        assert_eq!(p.source.to_string(), "10.7.0.1");
        assert_eq!(p.destination.to_string(), "10.7.0.2");
        assert_eq!(p.protocol, 1);
        assert_eq!(p.protocol_name(), "icmp");
        assert_eq!(p.ttl, 64);
        assert_eq!(p.total_length, 36);
        assert_eq!(
            p.transport,
            Transport::Icmp {
                icmp_type: 8,
                code: 0,
                id: Some(0x1234),
                sequence: Some(1),
            }
        );
        assert_eq!(p.payload_len, 8);
        assert_eq!(p.payload_preview, "abcdefgh");
        assert_eq!(
            p.payload_encoding, "utf8",
            "a printable payload is shown as text, and the event says so"
        );
    }

    #[test]
    fn the_event_data_is_structured_fields_and_never_raw_bytes() {
        let data = tun(&ipv4_icmp_echo_request()).unwrap().to_event_data();

        assert_eq!(data["direction"], "inbound");
        assert_eq!(data["ip_version"], 4);
        assert_eq!(data["source"], "10.7.0.1");
        assert_eq!(data["destination"], "10.7.0.2");
        assert_eq!(data["protocol"], "icmp");
        assert_eq!(data["protocol_number"], 1);
        assert_eq!(data["ttl"], 64);
        assert_eq!(data["total_length"], 36);
        assert_eq!(
            data["icmp_type"], "echo_request",
            "the model is given the name, not the number 8"
        );
        assert_eq!(data["icmp_type_number"], 8);
        assert_eq!(data["icmp_id"], 4660);
        assert_eq!(data["icmp_sequence"], 1);
        assert_eq!(data["payload_length"], 8);
        assert_eq!(data["payload_encoding"], "utf8");
        assert!(data["summary"].as_str().unwrap().contains("echo_request"));

        // The invariant behind "no raw bytes in event data": there is no field carrying the
        // packet, and hop_limit belongs to IPv6 only.
        assert!(data.get("hop_limit").is_none());
        assert!(data.get("packet_hex").is_none());
        assert!(data.get("data").is_none());
    }

    #[test]
    fn decodes_an_ipv4_tcp_syn_with_flag_names() {
        let p = tun(&ipv4_tcp_syn()).expect("decodes");

        assert_eq!(p.protocol_name(), "tcp");
        assert_eq!(p.ports(), Some((54321, 80)));
        match p.transport {
            Transport::Tcp {
                seq, ack, window, ..
            } => {
                assert_eq!(seq, 1);
                assert_eq!(ack, 0);
                assert_eq!(window, 65535);
            }
            other => panic!("expected TCP, got {other:?}"),
        }
        assert_eq!(p.payload_len, 0);
        assert_eq!(p.to_event_data()["tcp_flags"], json!(["syn"]));
    }

    #[test]
    fn decodes_an_ipv4_udp_datagram() {
        let p = tun(&ipv4_udp()).expect("decodes");

        assert_eq!(p.protocol_name(), "udp");
        assert_eq!(p.ports(), Some((40481, 53)));
        assert_eq!(p.total_length, 33);
        assert_eq!(p.payload_len, 5);
        assert_eq!(p.payload_preview, "hello");
    }

    #[test]
    fn decodes_an_ipv6_icmpv6_echo_request() {
        let p = tun(&ipv6_icmpv6_echo_request()).expect("decodes");

        assert_eq!(p.ip_version, 6);
        assert_eq!(p.source.to_string(), "2001:db8::1");
        assert_eq!(p.destination.to_string(), "2001:db8::2");
        assert_eq!(p.protocol_name(), "icmpv6");
        assert_eq!(p.ttl, 64, "the IPv6 hop limit lands in the same field");
        assert_eq!(p.total_length, 56, "40-byte header plus 16-byte payload");
        assert_eq!(
            p.transport,
            Transport::Icmp {
                icmp_type: 128,
                code: 0,
                id: Some(0xabcd),
                sequence: Some(7),
            }
        );

        let data = p.to_event_data();
        assert_eq!(data["hop_limit"], 64);
        assert!(
            data.get("ttl").is_none(),
            "IPv6 reports hop_limit, not ttl — the same number under the right name"
        );
        assert_eq!(
            data["icmp_type"], "echo_request",
            "128 is echo_request in ICMPv6 and something else entirely in ICMPv4"
        );
    }

    #[test]
    fn a_binary_payload_is_previewed_as_hex_and_says_so() {
        let mut frame = ipv4_udp();
        // Replace "hello" with five non-printable bytes.
        let n = frame.len();
        frame[n - 5..].copy_from_slice(&[0x00, 0x01, 0xff, 0xfe, 0x80]);

        let p = tun(&frame).expect("decodes");
        assert_eq!(p.payload_encoding, "hex");
        assert_eq!(p.payload_preview, "0001fffe80");
    }

    #[test]
    fn a_payload_longer_than_the_preview_reports_its_true_length() {
        let payload = vec![b'x'; 500];
        let packet = build_packet(&json!({
            "source": "10.0.0.1",
            "destination": "10.0.0.2",
            "protocol": "udp",
            "source_port": 1234,
            "destination_port": 5678,
            "payload": String::from_utf8(payload).unwrap(),
        }))
        .expect("builds");

        let p = tun(&packet).expect("decodes");
        assert_eq!(p.payload_len, 500);
        assert!(
            p.payload_preview.len() <= 80,
            "the preview is bounded; got {} chars",
            p.payload_preview.len()
        );
        assert_eq!(
            p.to_event_data()["payload_length"],
            500,
            "payload_length is the truth even when the preview is a fragment"
        );
    }

    #[test]
    fn an_unmodelled_protocol_still_reports_its_number() {
        let mut frame = ipv4_icmp_echo_request();
        frame[9] = 47; // GRE
        let p = tun(&frame).expect("decodes");
        assert_eq!(p.protocol, 47);
        assert_eq!(p.protocol_name(), "gre");
        assert_eq!(p.transport, Transport::Other);

        frame[9] = 253; // experimental, deliberately nameless here
        let p = tun(&frame).expect("decodes");
        assert_eq!(p.protocol_name(), "unknown");
        assert_eq!(
            p.to_event_data()["protocol_number"],
            253,
            "the number survives even when the name does not"
        );
    }

    #[test]
    fn truncated_frames_are_refused_rather_than_half_decoded() {
        assert!(matches!(
            tun(&ipv4_icmp_echo_request()[..12]),
            Err(DecodeError::TooShort { .. })
        ));
        assert!(matches!(
            tun(&ipv4_tcp_syn()[..30]),
            Err(DecodeError::TooShort { .. })
        ));
        assert!(matches!(tun(&[]), Err(DecodeError::TooShort { .. })));
        assert!(matches!(
            tun(&[0x35, 0, 0, 0]),
            Err(DecodeError::UnsupportedIpVersion(3))
        ));
        // IHL 4 claims a 16-byte header, which cannot hold the addresses.
        let mut bad = ipv4_icmp_echo_request();
        bad[0] = 0x44;
        assert!(matches!(tun(&bad), Err(DecodeError::BadIhl(4))));
    }

    // -----------------------------------------------------------------------
    // The 4-byte platform prefix — the off-by-four
    // -----------------------------------------------------------------------

    #[test]
    fn macos_utun_prepends_four_bytes_of_address_family() {
        let mut frame = vec![0x00, 0x00, 0x00, 0x02]; // AF_INET, big-endian
        frame.extend_from_slice(&ipv4_icmp_echo_request());

        let p = decode(&frame, PacketInformation::MacOsUtun, LinkMode::Tun).expect("decodes");
        assert_eq!(p.source.to_string(), "10.7.0.1");
        assert_eq!(p.total_length, 36);

        let mut v6 = vec![0x00, 0x00, 0x00, 0x1e]; // AF_INET6 on macOS is 30
        v6.extend_from_slice(&ipv6_icmpv6_echo_request());
        let p = decode(&v6, PacketInformation::MacOsUtun, LinkMode::Tun).expect("decodes");
        assert_eq!(p.ip_version, 6);
    }

    #[test]
    fn linux_packet_information_is_two_bytes_of_flags_and_an_ethertype() {
        let mut frame = vec![0x00, 0x00, 0x08, 0x00]; // flags 0, EtherType 0x0800
        frame.extend_from_slice(&ipv4_icmp_echo_request());
        let p = decode(&frame, PacketInformation::LinuxTunPi, LinkMode::Tun).expect("decodes");
        assert_eq!(p.protocol_name(), "icmp");

        let mut v6 = vec![0x00, 0x00, 0x86, 0xdd]; // EtherType 0x86DD
        v6.extend_from_slice(&ipv6_icmpv6_echo_request());
        let p = decode(&v6, PacketInformation::LinuxTunPi, LinkMode::Tun).expect("decodes");
        assert_eq!(p.ip_version, 6);
    }

    /// **The off-by-four, from both sides.**
    ///
    /// Getting this wrong is the single most common TUN bug, and the reason it costs a
    /// debugging pass is that it does not present as a misaligned header — every decoded field
    /// is simply wrong. Both mismatches must therefore be *errors*, not garbage.
    #[test]
    fn a_packet_information_mismatch_is_an_error_in_both_directions() {
        let mut prefixed = vec![0x00, 0x00, 0x00, 0x02];
        prefixed.extend_from_slice(&ipv4_icmp_echo_request());

        // Prefix present, configuration says there is none: the version nibble reads 0.
        assert!(
            matches!(
                decode(&prefixed, PacketInformation::None, LinkMode::Tun),
                Err(DecodeError::UnsupportedIpVersion(0))
            ),
            "reading a prefixed frame as bare must fail, not decode four bytes off"
        );

        // No prefix, configuration says there is one: 0x45000024 is neither AF_INET nor
        // AF_INET6, so the header is rejected rather than skipped.
        assert!(
            matches!(
                decode(
                    &ipv4_icmp_echo_request(),
                    PacketInformation::MacOsUtun,
                    LinkMode::Tun
                ),
                Err(DecodeError::BadPacketInformation { .. })
            ),
            "reading a bare frame as prefixed must fail, not swallow the first four bytes"
        );

        // A prefix naming something that is not IP is rejected too.
        let mut nonsense = vec![0x00, 0x00, 0x00, 0x07];
        nonsense.extend_from_slice(&ipv4_icmp_echo_request());
        assert!(matches!(
            decode(&nonsense, PacketInformation::MacOsUtun, LinkMode::Tun),
            Err(DecodeError::BadPacketInformation { .. })
        ));
    }

    #[test]
    fn the_prefix_written_back_matches_the_one_read() {
        for (pi, ipv6, expected) in [
            (PacketInformation::MacOsUtun, false, Some([0, 0, 0, 2])),
            (PacketInformation::MacOsUtun, true, Some([0, 0, 0, 30])),
            (
                PacketInformation::LinuxTunPi,
                false,
                Some([0, 0, 0x08, 0x00]),
            ),
            (
                PacketInformation::LinuxTunPi,
                true,
                Some([0, 0, 0x86, 0xdd]),
            ),
            (PacketInformation::None, false, None),
        ] {
            assert_eq!(pi.prefix_for(ipv6), expected, "{pi:?} ipv6={ipv6}");
        }

        // Round trip: prepend then strip gives back exactly the packet.
        let original = ipv4_icmp_echo_request();
        for pi in [
            PacketInformation::None,
            PacketInformation::MacOsUtun,
            PacketInformation::LinuxTunPi,
        ] {
            let mut framed = original.clone();
            pi.prepend(&mut framed).expect("prepends");
            assert_eq!(framed.len(), original.len() + pi.header_len());
            assert_eq!(pi.strip(&framed).expect("strips"), &original[..]);
        }
    }

    #[test]
    fn packet_information_modes_parse_from_the_startup_parameter() {
        assert_eq!(
            PacketInformation::parse("auto").unwrap(),
            PacketInformation::None
        );
        assert_eq!(
            PacketInformation::parse("macos_utun").unwrap(),
            PacketInformation::MacOsUtun
        );
        assert_eq!(
            PacketInformation::parse("linux_pi").unwrap(),
            PacketInformation::LinuxTunPi
        );
        assert!(PacketInformation::parse("sometimes").is_err());
    }

    // -----------------------------------------------------------------------
    // TAP / Ethernet
    // -----------------------------------------------------------------------

    #[test]
    fn tap_mode_decodes_the_ethernet_header() {
        let mut frame = vec![
            0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0x01, // destination MAC
            0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0x02, // source MAC
            0x08, 0x00, // EtherType IPv4
        ];
        frame.extend_from_slice(&ipv4_icmp_echo_request());

        let p = decode(&frame, PacketInformation::None, LinkMode::Tap).expect("decodes");
        let eth = p.ethernet.as_ref().expect("TAP carries a link header");
        assert_eq!(eth.destination_mac, "aa:bb:cc:dd:ee:01");
        assert_eq!(eth.source_mac, "aa:bb:cc:dd:ee:02");
        assert_eq!(p.source.to_string(), "10.7.0.1");

        let data = p.to_event_data();
        assert_eq!(data["ethernet"]["source_mac"], "aa:bb:cc:dd:ee:02");
        assert_eq!(data["ethernet"]["ethertype"], "0x0800");
    }

    #[test]
    fn tun_mode_reports_no_ethernet_header() {
        let p = tun(&ipv4_icmp_echo_request()).unwrap();
        assert!(p.ethernet.is_none());
        assert!(p.to_event_data().get("ethernet").is_none());
    }

    #[test]
    fn tap_refuses_a_frame_that_is_not_ip() {
        let frame = vec![
            0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0x01, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0x02, //
            0x08, 0x06, // ARP
            0x00, 0x01,
        ];
        assert!(matches!(
            decode(&frame, PacketInformation::None, LinkMode::Tap),
            Err(DecodeError::UnsupportedEtherType(0x0806))
        ));
    }

    // -----------------------------------------------------------------------
    // The escalation filter — the design's load-bearing gate
    // -----------------------------------------------------------------------

    fn matches(expr: &str, frame: &[u8]) -> bool {
        PacketFilter::parse(expr)
            .unwrap_or_else(|e| panic!("filter {expr:?} should parse: {e}"))
            .matches(&tun(frame).expect("fixture decodes"))
    }

    #[test]
    fn all_and_none_are_the_two_extremes() {
        assert!(matches("all", &ipv4_icmp_echo_request()));
        assert!(matches("all", &ipv4_tcp_syn()));
        assert!(!matches("none", &ipv4_icmp_echo_request()));
        assert!(PacketFilter::parse("none").unwrap().matches_nothing());
        assert!(!PacketFilter::parse("all").unwrap().matches_nothing());
    }

    #[test]
    fn the_default_filter_admits_pings_and_nothing_else() {
        assert!(matches("icmp", &ipv4_icmp_echo_request()));
        assert!(!matches("icmp", &ipv4_tcp_syn()));
        assert!(!matches("icmp", &ipv4_udp()));
        assert!(
            !matches("icmp", &ipv6_icmpv6_echo_request()),
            "icmp is protocol 1; ICMPv6 is 58 and must be asked for by name"
        );
        assert!(matches("icmpv6", &ipv6_icmpv6_echo_request()));
    }

    /// `tcp-syn` is the term that makes the whole design work at TCP volume: one event per
    /// connection attempt rather than one per packet.
    #[test]
    fn tcp_syn_matches_a_new_connection_and_not_the_rest_of_it() {
        assert!(matches("tcp-syn", &ipv4_tcp_syn()));
        assert!(
            !matches("tcp-syn", &ipv4_tcp_syn_ack()),
            "SYN+ACK is the other side answering, not a new connection"
        );

        let mut established = ipv4_tcp_syn();
        established[33] = 0x10; // plain ACK
        assert!(!matches("tcp-syn", &established));
        established[33] = 0x18; // PSH|ACK — data on an open connection
        assert!(!matches("tcp-syn", &established));
    }

    #[test]
    fn ports_addresses_and_versions_all_filter() {
        assert!(matches("tcp:80", &ipv4_tcp_syn()));
        assert!(
            matches("tcp:54321", &ipv4_tcp_syn()),
            "either endpoint counts"
        );
        assert!(!matches("tcp:443", &ipv4_tcp_syn()));
        assert!(matches("udp:53", &ipv4_udp()));
        assert!(
            !matches("tcp:53", &ipv4_udp()),
            "the transport must match too"
        );
        assert!(matches("port:53", &ipv4_udp()));

        assert!(matches("to:10.7.0.2", &ipv4_icmp_echo_request()));
        assert!(!matches("to:10.7.0.1", &ipv4_icmp_echo_request()));
        assert!(matches("from:10.7.0.1", &ipv4_icmp_echo_request()));
        assert!(matches("host:10.7.0.2", &ipv4_icmp_echo_request()));
        assert!(matches("host:10.7.0.1", &ipv4_icmp_echo_request()));

        assert!(matches("v4", &ipv4_udp()));
        assert!(!matches("v6", &ipv4_udp()));
        assert!(matches("v6", &ipv6_icmpv6_echo_request()));

        assert!(matches("ip-proto-1", &ipv4_icmp_echo_request()));
        assert!(!matches("ip-proto-6", &ipv4_icmp_echo_request()));
    }

    #[test]
    fn plus_is_and_and_comma_is_or() {
        let expr = "tcp-syn+to:192.168.1.1, icmp";
        assert!(matches(expr, &ipv4_tcp_syn()), "a SYN to the named host");
        assert!(matches(expr, &ipv4_icmp_echo_request()), "or any ping");
        assert!(!matches(expr, &ipv4_udp()));
        assert!(
            !matches("tcp-syn+to:10.0.0.9", &ipv4_tcp_syn()),
            "both halves of an AND must hold"
        );
    }

    #[test]
    fn a_malformed_filter_is_refused_at_startup_with_a_useful_message() {
        for expr in [
            "",
            "wat",
            "icmp,,udp",
            "tcp:notaport",
            "from:notanaddress",
            "ip-proto-999",
            "icmp:80",
        ] {
            let err = PacketFilter::parse(expr)
                .expect_err(&format!("{expr:?} must not parse"))
                .to_string();
            assert!(
                !err.is_empty(),
                "a rejection has to say what was wrong with {expr:?}"
            );
        }
        // "icmp:80" is refused specifically because ICMP has no ports to match on.
        assert!(PacketFilter::parse("icmp:80")
            .unwrap_err()
            .contains("no ports"));
    }

    // -----------------------------------------------------------------------
    // Building
    // -----------------------------------------------------------------------

    /// Verify a checksummed span sums to zero, which is the property a receiving stack checks.
    fn checksum_is_valid(span: &[u8]) -> bool {
        checksum16(span) == 0
    }

    #[test]
    fn builds_an_icmp_echo_reply_that_decodes_back_to_what_was_asked_for() {
        let bytes = build_packet(&json!({
            "source": "10.7.0.2",
            "destination": "10.7.0.1",
            "protocol": "icmp",
            "icmp_type": "echo_reply",
            "icmp_id": 4660,
            "icmp_sequence": 1,
            "ttl": 64,
            "payload": "abcdefgh",
            "payload_encoding": "utf8"
        }))
        .expect("builds");

        let p = tun(&bytes).expect("decodes");
        assert_eq!(p.source.to_string(), "10.7.0.2");
        assert_eq!(p.destination.to_string(), "10.7.0.1");
        assert_eq!(p.ttl, 64);
        assert_eq!(p.total_length, bytes.len());
        assert_eq!(
            p.transport,
            Transport::Icmp {
                icmp_type: 0,
                code: 0,
                id: Some(4660),
                sequence: Some(1)
            }
        );
        assert_eq!(p.payload_preview, "abcdefgh");

        assert!(
            checksum_is_valid(&bytes[..20]),
            "the IPv4 header checksum must verify — the host's stack is what actually checks it"
        );
        assert!(
            checksum_is_valid(&bytes[20..]),
            "the ICMPv4 checksum covers the message with no pseudo-header"
        );
    }

    #[test]
    fn builds_a_udp_datagram_with_a_valid_pseudo_header_checksum() {
        let bytes = build_packet(&json!({
            "source": "10.0.0.1",
            "destination": "10.0.0.2",
            "protocol": "udp",
            "source_port": 1234,
            "destination_port": 53,
            "payload": "hello"
        }))
        .expect("builds");

        let p = tun(&bytes).expect("decodes");
        assert_eq!(p.ports(), Some((1234, 53)));
        assert_eq!(p.payload_preview, "hello");
        assert!(checksum_is_valid(&bytes[..20]));

        // UDP's checksum covers the IPv4 pseudo-header followed by the datagram.
        let mut span = vec![
            10, 0, 0, 1, // source
            10, 0, 0, 2, // destination
            0, 17, // zero, protocol
        ];
        let udp = &bytes[20..];
        span.extend_from_slice(&(udp.len() as u16).to_be_bytes());
        span.extend_from_slice(udp);
        assert!(checksum_is_valid(&span));
    }

    #[test]
    fn builds_a_tcp_segment_with_the_named_flags() {
        let bytes = build_packet(&json!({
            "source": "10.0.0.1",
            "destination": "10.0.0.2",
            "protocol": "tcp",
            "source_port": 80,
            "destination_port": 54321,
            "flags": ["syn", "ack"],
            "seq": 900,
            "ack": 2,
            "window": 8192
        }))
        .expect("builds");

        let p = tun(&bytes).expect("decodes");
        match p.transport {
            Transport::Tcp {
                source_port,
                destination_port,
                seq,
                ack,
                flags,
                window,
            } => {
                assert_eq!((source_port, destination_port), (80, 54321));
                assert_eq!(seq, 900);
                assert_eq!(ack, 2);
                assert_eq!(window, 8192);
                assert_eq!(tcp_flag_names(flags), vec!["syn", "ack"]);
            }
            other => panic!("expected TCP, got {other:?}"),
        }
    }

    #[test]
    fn builds_an_icmpv6_echo_reply_whose_checksum_covers_the_pseudo_header() {
        let bytes = build_packet(&json!({
            "source": "2001:db8::2",
            "destination": "2001:db8::1",
            "protocol": "icmpv6",
            "icmp_type": "echo_reply",
            "icmp_id": 43981,
            "icmp_sequence": 7,
            "payload": "12345678"
        }))
        .expect("builds");

        let p = tun(&bytes).expect("decodes");
        assert_eq!(p.ip_version, 6);
        assert_eq!(p.protocol_name(), "icmpv6");
        assert_eq!(
            p.transport,
            Transport::Icmp {
                icmp_type: 129,
                code: 0,
                id: Some(43981),
                sequence: Some(7)
            }
        );

        let icmp = &bytes[40..];
        let mut span = bytes[8..40].to_vec(); // source + destination
        span.extend_from_slice(&(icmp.len() as u32).to_be_bytes());
        span.extend_from_slice(&[0, 0, 0, 58]);
        span.extend_from_slice(icmp);
        assert!(
            checksum_is_valid(&span),
            "ICMPv6, unlike ICMPv4, checksums over the IPv6 pseudo-header"
        );
    }

    /// The `payload_encoding` field is honoured, not sniffed.
    ///
    /// `"48656c6c6f"` is simultaneously valid text and valid hex; only the sender knows which
    /// it meant. This is the `send_tcp_data` bug the root `CLAUDE.md` records, and it must not
    /// be reintroduced here.
    #[test]
    fn the_payload_encoding_field_decides_and_is_never_guessed() {
        let ambiguous = "48656c6c6f";

        let as_hex = build_packet(&json!({
            "source": "10.0.0.1", "destination": "10.0.0.2", "protocol": "udp",
            "source_port": 1, "destination_port": 2,
            "payload": ambiguous, "payload_encoding": "hex"
        }))
        .expect("builds");
        assert_eq!(&as_hex[28..], b"Hello", "hex must actually be decoded");

        let as_text = build_packet(&json!({
            "source": "10.0.0.1", "destination": "10.0.0.2", "protocol": "udp",
            "source_port": 1, "destination_port": 2,
            "payload": ambiguous, "payload_encoding": "utf8"
        }))
        .expect("builds");
        assert_eq!(
            &as_text[28..],
            ambiguous.as_bytes(),
            "the same string as text is ten bytes, not five"
        );

        let default = build_packet(&json!({
            "source": "10.0.0.1", "destination": "10.0.0.2", "protocol": "udp",
            "source_port": 1, "destination_port": 2,
            "payload": ambiguous
        }))
        .expect("builds");
        assert_eq!(&default[28..], ambiguous.as_bytes(), "the default is utf8");
    }

    #[test]
    fn invalid_hex_is_refused_rather_than_sent_as_text() {
        let err = build_packet(&json!({
            "source": "10.0.0.1", "destination": "10.0.0.2", "protocol": "udp",
            "source_port": 1, "destination_port": 2,
            "payload": "zzz", "payload_encoding": "hex"
        }))
        .expect_err("must refuse");
        assert!(err.to_string().contains("hex"));
    }

    #[test]
    fn builds_an_ethernet_frame_when_both_macs_are_named() {
        let bytes = build_packet(&json!({
            "source": "10.7.0.2",
            "destination": "10.7.0.1",
            "protocol": "icmp",
            "icmp_type": "echo_reply",
            "source_mac": "aa:bb:cc:dd:ee:02",
            "destination_mac": "aa:bb:cc:dd:ee:01"
        }))
        .expect("builds");

        let p = decode(&bytes, PacketInformation::None, LinkMode::Tap).expect("decodes as TAP");
        let eth = p.ethernet.expect("has a link header");
        assert_eq!(eth.source_mac, "aa:bb:cc:dd:ee:02");
        assert_eq!(eth.destination_mac, "aa:bb:cc:dd:ee:01");

        // Exactly one MAC is a mistake, not a default.
        assert!(build_packet(&json!({
            "source": "10.7.0.2", "destination": "10.7.0.1",
            "protocol": "icmp", "icmp_type": "echo_reply",
            "source_mac": "aa:bb:cc:dd:ee:02"
        }))
        .is_err());
    }

    #[test]
    fn refuses_the_packets_it_cannot_honestly_build() {
        let cases: Vec<(&str, serde_json::Value)> = vec![
            (
                "mixed address families",
                json!({"source": "10.0.0.1", "destination": "2001:db8::1", "protocol": "udp",
                       "source_port": 1, "destination_port": 2}),
            ),
            (
                "icmp over IPv6",
                json!({"source": "2001:db8::1", "destination": "2001:db8::2",
                       "protocol": "icmp", "icmp_type": "echo_reply"}),
            ),
            (
                "icmpv6 over IPv4",
                json!({"source": "10.0.0.1", "destination": "10.0.0.2",
                       "protocol": "icmpv6", "icmp_type": "echo_reply"}),
            ),
            (
                "ip_version contradicting the addresses",
                json!({"source": "10.0.0.1", "destination": "10.0.0.2", "protocol": "icmp",
                       "icmp_type": "echo_reply", "ip_version": 6}),
            ),
            (
                "an unknown protocol name",
                json!({"source": "10.0.0.1", "destination": "10.0.0.2", "protocol": "quux"}),
            ),
            (
                "an unknown TCP flag",
                json!({"source": "10.0.0.1", "destination": "10.0.0.2", "protocol": "tcp",
                       "source_port": 1, "destination_port": 2, "flags": ["synn"]}),
            ),
            (
                "TCP without ports",
                json!({"source": "10.0.0.1", "destination": "10.0.0.2", "protocol": "tcp"}),
            ),
            (
                "ICMP without a type",
                json!({"source": "10.0.0.1", "destination": "10.0.0.2", "protocol": "icmp"}),
            ),
            (
                "no source at all",
                json!({"destination": "10.0.0.2", "protocol": "icmp", "icmp_type": "echo_reply"}),
            ),
        ];

        for (why, action) in cases {
            assert!(
                build_packet(&action).is_err(),
                "{why} must be refused — guessing here would put a packet on a real \
                 interface that nobody described"
            );
        }
    }

    #[test]
    fn flag_names_round_trip() {
        assert_eq!(tcp_flag_bits(&["syn".to_string()]).unwrap(), 0x02);
        assert_eq!(tcp_flag_bits(&["fin".into(), "ack".into()]).unwrap(), 0x11);
        assert_eq!(tcp_flag_names(0x12), vec!["syn", "ack"]);
        assert_eq!(tcp_flag_names(0), Vec::<&str>::new());
        assert!(tcp_flag_bits(&["nope".to_string()]).is_err());
    }

    #[test]
    fn mac_addresses_parse_and_render() {
        assert_eq!(
            parse_mac("aa:bb:cc:dd:ee:ff").unwrap(),
            [0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff]
        );
        assert_eq!(parse_mac("AA-BB-CC-DD-EE-FF").unwrap()[0], 0xaa);
        assert!(parse_mac("aa:bb:cc").is_err());
        assert!(parse_mac("aa:bb:cc:dd:ee:zz").is_err());
    }

    #[test]
    fn protocol_numbers_and_names_agree() {
        for (n, name) in [
            (1u8, "icmp"),
            (6, "tcp"),
            (17, "udp"),
            (58, "icmpv6"),
            (89, "ospf"),
        ] {
            assert_eq!(ip_protocol_name(n), name);
        }
        assert_eq!(ip_protocol_name(253), "unknown");
    }

    /// The `send_packet` example is what the model copies, so it has to build.
    ///
    /// `executable_examples_test` covers this across the whole registry; asserting it here as
    /// well means a change to the example fails in the protocol's own suite, where whoever
    /// made it is looking.
    #[test]
    fn the_declared_send_packet_example_builds() {
        let example = netget::server::tuntap::actions::send_packet_action().example;
        build_packet(&example).expect("the advertised example must build");
    }
}
