//! Client protocol e2e tests

#[cfg(feature = "amqp")]
pub mod amqp;
#[cfg(feature = "arp")]
pub mod arp;
#[cfg(feature = "bgp")]
pub mod bgp;
#[cfg(feature = "bitcoin")]
pub mod bitcoin;
#[cfg(feature = "bluetooth-ble-client")]
pub mod bluetooth;
#[cfg(feature = "bootp")]
pub mod bootp;
#[cfg(feature = "cassandra")]
pub mod cassandra;
#[cfg(feature = "couchdb")]
pub mod couchdb;
#[cfg(feature = "datalink")]
pub mod datalink;
#[cfg(feature = "dc")]
pub mod dc;
#[cfg(feature = "dhcp")]
pub mod dhcp;
#[cfg(feature = "dns")]
pub mod dns;
#[cfg(feature = "doh")]
pub mod doh;
#[cfg(feature = "dot")]
pub mod dot;
#[cfg(any(feature = "dynamo", feature = "dynamodb"))]
pub mod dynamodb;
#[cfg(feature = "elasticsearch")]
pub mod elasticsearch;
#[cfg(feature = "etcd")]
pub mod etcd;
#[cfg(feature = "ftp")]
pub mod ftp;
#[cfg(feature = "git")]
pub mod git;
#[cfg(feature = "grpc")]
pub mod grpc;
#[cfg(feature = "http")]
pub mod http;
#[cfg(feature = "http2")]
pub mod http2;
#[cfg(feature = "http3")]
pub mod http3;
#[cfg(feature = "http_proxy")]
pub mod http_proxy;
#[cfg(feature = "icmp")]
pub mod icmp;
#[cfg(feature = "igmp")]
pub mod igmp;
#[cfg(feature = "imap")]
pub mod imap;
#[cfg(feature = "ipp")]
pub mod ipp;
#[cfg(feature = "irc")]
pub mod irc;
#[cfg(feature = "isis")]
pub mod isis;
#[cfg(feature = "jsonrpc")]
pub mod jsonrpc;
#[cfg(feature = "kafka")]
pub mod kafka;
#[cfg(feature = "kubernetes")]
pub mod kubernetes;
#[cfg(feature = "ldap")]
pub mod ldap;
#[cfg(feature = "maven")]
pub mod maven;
#[cfg(feature = "mcp")]
pub mod mcp;
#[cfg(feature = "mdns")]
pub mod mdns;
#[cfg(feature = "mongodb")]
pub mod mongodb;
#[cfg(feature = "mqtt")]
pub mod mqtt;
#[cfg(feature = "mssql")]
pub mod mssql;
#[cfg(feature = "mysql")]
pub mod mysql;
#[cfg(feature = "nfc-client")]
pub mod nfc;
#[cfg(feature = "nfs")]
pub mod nfs;
#[cfg(feature = "nntp")]
pub mod nntp;
#[cfg(feature = "npm")]
pub mod npm;
#[cfg(feature = "ntp")]
pub mod ntp;
#[cfg(feature = "oauth2")]
pub mod oauth2;
#[cfg(feature = "ollama")]
pub mod ollama;
#[cfg(feature = "openai")]
pub mod openai;
#[cfg(feature = "openapi")]
pub mod openapi;
#[cfg(feature = "openidconnect")]
pub mod openidconnect;
#[cfg(feature = "ospf")]
pub mod ospf;
#[cfg(feature = "pop3")]
pub mod pop3;
#[cfg(feature = "postgresql")]
pub mod postgresql;
#[cfg(feature = "pypi")]
pub mod pypi;
#[cfg(feature = "redis")]
pub mod redis;
#[cfg(feature = "rip")]
pub mod rip;
#[cfg(feature = "rss")]
pub mod rss;
#[cfg(feature = "s3")]
pub mod s3;
#[cfg(feature = "saml")]
pub mod saml;
#[cfg(feature = "sip")]
pub mod sip;
#[cfg(feature = "smb")]
pub mod smb;
#[cfg(feature = "smtp")]
pub mod smtp;
#[cfg(feature = "snmp")]
pub mod snmp;
#[cfg(feature = "socket_file")]
pub mod socket_file;
#[cfg(feature = "socks5")]
pub mod socks5;
#[cfg(feature = "sqs")]
pub mod sqs;
#[cfg(feature = "ssh")]
pub mod ssh;
#[cfg(all(feature = "ssh-agent", unix))]
pub mod ssh_agent;
#[cfg(feature = "stun")]
pub mod stun;
#[cfg(feature = "syslog")]
pub mod syslog;
#[cfg(feature = "tcp")]
pub mod tcp;
#[cfg(feature = "telnet")]
pub mod telnet;
#[cfg(feature = "tftp")]
pub mod tftp;
#[cfg(feature = "tls")]
pub mod tls;
#[cfg(feature = "tor")]
pub mod tor;
#[cfg(feature = "torrent-dht")]
pub mod torrent_dht;
#[cfg(feature = "torrent-peer")]
pub mod torrent_peer;
#[cfg(feature = "torrent-tracker")]
pub mod torrent_tracker;
#[cfg(feature = "turn")]
pub mod turn;
#[cfg(feature = "udp")]
pub mod udp;
#[cfg(feature = "usb")]
pub mod usb;
#[cfg(feature = "vnc")]
pub mod vnc;
#[cfg(feature = "webdav")]
pub mod webdav;
#[cfg(feature = "webrtc")]
pub mod webrtc;
#[cfg(feature = "websocket")]
pub mod websocket;
#[cfg(feature = "whois")]
pub mod whois;
#[cfg(feature = "gopher")]
pub mod gopher;
#[cfg(feature = "finger")]
pub mod finger;
#[cfg(feature = "ident")]
pub mod ident;
#[cfg(feature = "llmnr")]
pub mod llmnr;
#[cfg(feature = "wireguard")]
pub mod wireguard;
#[cfg(feature = "xmlrpc")]
pub mod xmlrpc;
#[cfg(feature = "xmpp")]
pub mod xmpp;
#[cfg(feature = "zookeeper")]
pub mod zookeeper;
