// capnproto.org/go/capnp/v3, unchanged, in either role over directory.capnp (code generated by
// capnpc-go into directory/). Prints one JSON line.
//
//	capnp-peer client HOST:PORT   call every method on the bootstrap capability
//	capnp-peer server             serve Directory on 127.0.0.1, print READY <addr>
package main

import (
	"context"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"os"
	"time"

	"capnproto.org/go/capnp/v3"
	"capnproto.org/go/capnp/v3/rpc"

	"netget.test/capnp-peer/directory"
)

func entryJSON(e directory.Entry) map[string]any {
	name, _ := e.Name()
	tags, _ := e.Tags()
	var tl []string
	for i := 0; i < tags.Len(); i++ {
		t, _ := tags.At(i)
		tl = append(tl, t)
	}
	scores, _ := e.Scores()
	var sl []float64
	for i := 0; i < scores.Len(); i++ {
		sl = append(sl, scores.At(i))
	}
	children, _ := e.Children()
	var cl []any
	for i := 0; i < children.Len(); i++ {
		cl = append(cl, entryJSON(children.At(i)))
	}
	out := map[string]any{
		"name": name, "size": e.Size(), "kind": e.Kind().String(), "tags": tl,
		"priority": e.Priority(), "owner": map[string]any{"uid": e.Owner().Uid(), "gid": e.Owner().Gid()},
		"which": e.Which().String(), "scores": sl, "hidden": e.Hidden(), "children": cl,
	}
	switch e.Which() {
	case directory.Entry_Which_target:
		t, _ := e.Target()
		out["target"] = t
	case directory.Entry_Which_blob:
		b, _ := e.Blob()
		out["blob"] = hex.EncodeToString(b)
	}
	return out
}

func fillEntry(e directory.Entry) error {
	e.SetName("src")
	e.SetSize(4096)
	e.SetKind(directory.Kind_directory)
	tags, _ := e.NewTags(2)
	tags.Set(0, "code")
	tags.Set(1, "go")
	e.Owner().SetUid(1000)
	e.Owner().SetGid(100)
	e.SetTarget("/srv/src")
	scores, _ := e.NewScores(2)
	scores.Set(0, 1.5)
	scores.Set(1, -2.25)
	e.SetHidden(false)
	children, _ := e.NewChildren(1)
	c := children.At(0)
	c.SetName("main.go")
	c.SetSize(12)
	c.SetPriority(-3)
	return c.SetBlob([]byte{0, 0xff, 'h', 'i'})
}

func client(addr string) map[string]any {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	c, err := net.Dial("tcp", addr)
	if err != nil {
		panic(err)
	}
	conn := rpc.NewConn(rpc.NewStreamTransport(c), nil)
	defer conn.Close()
	d := directory.Directory(conn.Bootstrap(ctx))
	out := map[string]any{}
	ping, rel := d.Ping(ctx, nil)
	pr, err := ping.Struct()
	if err != nil {
		panic(err)
	}
	out["ping"], _ = pr.Pong()
	rel()
	add, rel := d.Add(ctx, func(p directory.Directory_add_Params) error { p.SetA(40); p.SetB(2); return nil })
	ar, err := add.Struct()
	if err != nil {
		panic(err)
	}
	out["add"] = ar.Sum()
	rel()
	look, rel := d.Lookup(ctx, func(p directory.Directory_lookup_Params) error { return p.SetName("readme") })
	lr, err := look.Struct()
	if err != nil {
		panic(err)
	}
	le, _ := lr.Entry()
	out["lookup"] = entryJSON(le)
	rel()
	store, rel := d.Store(ctx, func(p directory.Directory_store_Params) error {
		e, err := p.NewEntry()
		if err != nil {
			return err
		}
		return fillEntry(e)
	})
	sr, err := store.Struct()
	if err != nil {
		panic(err)
	}
	se, _ := sr.Stored()
	out["stored"] = entryJSON(se)
	out["count"] = sr.Count()
	rel()
	fail, rel := d.Fail(ctx, func(p directory.Directory_fail_Params) error { return p.SetWhy("on purpose") })
	_, err = fail.Struct()
	out["fail"] = fmt.Sprint(err)
	rel()
	// Several calls in flight at once.
	var futures []directory.Directory_add_Results_Future
	for i := 0; i < 5; i++ {
		n := int32(i)
		f, r := d.Add(ctx, func(p directory.Directory_add_Params) error { p.SetA(n); p.SetB(n); return nil })
		defer r()
		futures = append(futures, f)
	}
	var sums []int64
	for _, f := range futures {
		r, err := f.Struct()
		if err != nil {
			panic(err)
		}
		sums = append(sums, r.Sum())
	}
	out["pipelined"] = sums
	return out
}

type server struct{}

func (server) Ping(ctx context.Context, call directory.Base_ping) error {
	r, err := call.AllocResults()
	if err != nil {
		return err
	}
	return r.SetPong("pong from go-capnp")
}

func (server) Add(ctx context.Context, call directory.Directory_add) error {
	r, err := call.AllocResults()
	if err != nil {
		return err
	}
	r.SetSum(int64(call.Args().A()) + int64(call.Args().B()))
	return nil
}

func (server) Lookup(ctx context.Context, call directory.Directory_lookup) error {
	name, _ := call.Args().Name()
	if name == "missing" {
		return errors.New("no entry named missing")
	}
	r, err := call.AllocResults()
	if err != nil {
		return err
	}
	e, err := r.NewEntry()
	if err != nil {
		return err
	}
	e.SetName(name)
	e.SetSize(1234)
	e.SetKind(directory.Kind_file)
	tags, _ := e.NewTags(2)
	tags.Set(0, "doc")
	tags.Set(1, name)
	e.Owner().SetUid(501)
	e.SetTarget("/docs/" + name)
	scores, _ := e.NewScores(1)
	scores.Set(0, 0.5)
	return nil
}

func (server) Store(ctx context.Context, call directory.Directory_store) error {
	in, err := call.Args().Entry()
	if err != nil {
		return err
	}
	r, err := call.AllocResults()
	if err != nil {
		return err
	}
	if err := r.SetStored(in); err != nil {
		return err
	}
	children, _ := in.Children()
	r.SetCount(uint32(children.Len() + 1))
	return nil
}

func (server) Fail(ctx context.Context, call directory.Directory_fail) error {
	why, _ := call.Args().Why()
	return errors.New("refused: " + why)
}

func serve() {
	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		panic(err)
	}
	fmt.Println("READY", l.Addr().String())
	boot := capnp.Client(directory.Directory_ServerToClient(server{}))
	for {
		c, err := l.Accept()
		if err != nil {
			panic(err)
		}
		go func() {
			conn := rpc.NewConn(rpc.NewStreamTransport(c), &rpc.Options{BootstrapClient: boot.AddRef()})
			<-conn.Done()
		}()
	}
}

func main() {
	if os.Args[1] == "server" {
		serve()
		return
	}
	b, _ := json.Marshal(client(os.Args[2]))
	fmt.Println(string(b))
}
