//! RSS client tests.
//!
//! The client was re-enabled in August 2026 after sitting commented out of the registry since
//! November 2025 (`e16ffb2d`, "client needs API updates"). It had no tests before, and could
//! not have had any — nothing unregistered runs.
//!
//! **Peer honesty:** the feed is served by a plain in-test TCP listener writing RSS 2.0 XML
//! that was hand-written from the specification, not generated by the `rss` crate this client
//! parses with. So the parse is checked against bytes produced independently of the parser.
//! What is *not* independent is the HTTP server, which is a few lines in this file rather
//! than a real one.

#![cfg(feature = "rss")]

use super::super::super::helpers::{self, E2EResult, NetGetConfig};
use netget::client::rss::resolve_feed_url;
use std::sync::Arc;
use std::time::Duration;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpListener;
use tokio::sync::Mutex;

// ===========================================================================
// URL resolution
// ===========================================================================

/// The model may give a bare path or a full URL, and both must work. This is the kind of
/// thing that silently sends a request to the wrong host if it is wrong.
#[test]
fn resolves_paths_against_the_base_and_leaves_absolute_urls_alone() {
    assert_eq!(
        resolve_feed_url("http://127.0.0.1:8080", "/news.xml"),
        "http://127.0.0.1:8080/news.xml"
    );
    assert_eq!(
        resolve_feed_url("http://127.0.0.1:8080/", "/news.xml"),
        "http://127.0.0.1:8080/news.xml"
    );
    assert_eq!(
        resolve_feed_url("http://127.0.0.1:8080", "news.xml"),
        "http://127.0.0.1:8080/news.xml"
    );
    assert_eq!(
        resolve_feed_url("http://127.0.0.1:8080", "http://127.0.0.1:9999/other.xml"),
        "http://127.0.0.1:9999/other.xml",
        "an absolute URL must not be rewritten"
    );
}

// ===========================================================================
// E2E: the client against a hand-written RSS 2.0 feed, LLM mocked
// ===========================================================================

/// RSS 2.0, written from the specification rather than emitted by the `rss` crate, so the
/// parse is checked against bytes the parser did not produce.
const FEED_XML: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>Fake Tech News</title>
    <link>http://example.invalid/</link>
    <description>Entirely invented headlines</description>
    <item>
      <title>First headline</title>
      <link>http://example.invalid/1</link>
      <description>Something happened</description>
      <author>alice@example.invalid</author>
      <pubDate>Mon, 09 Nov 2026 12:00:00 GMT</pubDate>
      <guid>http://example.invalid/1</guid>
    </item>
    <item>
      <title>Second headline</title>
      <link>http://example.invalid/2</link>
      <description>Something else happened</description>
      <pubDate>Mon, 09 Nov 2026 13:00:00 GMT</pubDate>
    </item>
  </channel>
</rss>
"#;

/// Serve `FEED_XML` on any GET, and record the paths requested. Bound to loopback only.
async fn start_feed_server(paths: Arc<Mutex<Vec<String>>>) -> E2EResult<u16> {
    let listener = TcpListener::bind("127.0.0.1:0").await?;
    let port = listener.local_addr()?.port();

    tokio::spawn(async move {
        loop {
            let Ok((mut stream, _)) = listener.accept().await else {
                return;
            };
            let paths = paths.clone();
            tokio::spawn(async move {
                let mut buf = vec![0u8; 4096];
                let Ok(n) = stream.read(&mut buf).await else {
                    return;
                };
                let request = String::from_utf8_lossy(&buf[..n]).into_owned();
                if let Some(line) = request.lines().next() {
                    if let Some(path) = line.split_whitespace().nth(1) {
                        paths.lock().await.push(path.to_string());
                    }
                }
                let response = format!(
                    "HTTP/1.1 200 OK\r\nContent-Type: application/rss+xml\r\n\
                     Content-Length: {}\r\nConnection: close\r\n\r\n{}",
                    FEED_XML.len(),
                    FEED_XML
                );
                let _ = stream.write_all(response.as_bytes()).await;
                let _ = stream.flush().await;
            });
        }
    });

    Ok(port)
}

/// The client fetches the feed the model named, parses it, and hands the model **structured
/// items rather than XML** — the point of the protocol. The mock asserts that by refusing to
/// disconnect unless the item titles arrived intact.
#[tokio::test]
async fn fetches_and_parses_a_feed_into_structured_items() -> E2EResult<()> {
    let paths = Arc::new(Mutex::new(Vec::new()));
    let port = start_feed_server(paths.clone()).await?;

    let config = NetGetConfig::new(format!(
        "connect to 127.0.0.1:{} via rss and fetch /tech-news.xml",
        port
    ))
    .with_log_level("debug")
    .with_mock(|mock| {
        mock.on_event("rss_feed_fetched")
            .respond_with_actions_from_event(|event| {
                // Derived from the event: if the feed was mis-parsed, this becomes a second
                // fetch of a path the server records, and the assertions below fail.
                let title = event["feed_title"].as_str().unwrap_or("");
                let count = event["item_count"].as_u64().unwrap_or(0);
                let first = event["items"][0]["title"].as_str().unwrap_or("");
                let author = event["items"][0]["author"].as_str().unwrap_or("");
                if title == "Fake Tech News"
                    && count == 2
                    && first == "First headline"
                    && author == "alice@example.invalid"
                {
                    serde_json::json!([{ "type": "disconnect" }])
                } else {
                    serde_json::json!([{
                        "type": "fetch_rss_feed",
                        "url": "/PARSE-WAS-WRONG.xml"
                    }])
                }
            })
            .expect_calls(1)
            .and()
            .on_event("rss_connected")
            .respond_with_actions(serde_json::json!([{
                "type": "fetch_rss_feed",
                "url": "/tech-news.xml"
            }]))
            .expect_calls(1)
            .and()
            .on_instruction_containing("via rss")
            .respond_with_actions_from_event(move |_| {
                serde_json::json!([{
                    "type": "open_client",
                    "remote_addr": format!("127.0.0.1:{}", port),
                    "base_stack": "rss",
                    "instruction": "Fetch /tech-news.xml and summarise it"
                }])
            })
            .expect_calls(1)
            .and()
    });

    let client = helpers::start_netget_client(config).await?;
    tokio::time::sleep(Duration::from_secs(5)).await;

    let requested = paths.lock().await.clone();
    assert_eq!(
        requested,
        vec!["/tech-news.xml".to_string()],
        "exactly the path the model asked for, resolved against the client's base address. \
         A '/PARSE-WAS-WRONG.xml' here means the parsed feed did not reach the model \
         intact. Client output: {:?}",
        client.get_output().await
    );

    // Wait for the exchange the mocks describe, rather than trusting a fixed
    // sleep to have covered it. Under load the last response routinely lands
    // after the sleep expires, and the test reports it as never having happened.
    client.wait_for_mocks(30).await;
    client.verify_mocks().await?;
    client.stop().await?;
    Ok(())
}
